### ISSUE TITLE
Lists are being used in situations where they don't seem to make sense

### ISSUE THREAD

**Issue by treeowl** [haskell/time#1]
I haven't tracked down where things are defined, but `Data.Time.Format`  uses `months` and `wDays` functions that return lists representing the mapping from numbers to month and day names. The obvious approach, I think, would just be to return a *function* from each of these instead of a list.

**Comment by AshleyYakeley** [comment]
Functions are out because they're not instances of `Eq` or `Show`. Lists are easier to deal with and understand than `Array`.
