### ISSUE TITLE
Parsing from Unix seconds to LocalTime

### ISSUE THREAD

**Issue by waiting-for-dev** [haskell/time#104]
```haskell
:m +Data.Time
parseTimeM True defaultTimeLocale "%s" "1535684406" :: Maybe UTCTime
-- => Just 2018-08-31 03:00:06 UTC
parseTimeM True defaultTimeLocale "%s" "1535684406" :: Maybe LocalTime
-- => Just 1970-01-01 00:00:00
```

Is it a bug?

**Comment by waiting-for-dev** [comment]
Sorry, I miss that in the docs... But, anyway, does it make sense? Why can't we parse a `LocalTime` from `%s`?. In the example before, I think it should parse to `Just 2018-08-31 03:00:06`.

I guess it is because in Unix time we have time zone information (UTC), so the resulting local time (which in theory doesn't have time zone attached) would have an "implicit" UTC timezone. I guess that the recommended approach is to parse `%s` to `UTCTime` and from there convert to `LocalTime` providing a `TimeZone` with `utcToLocalTime`.

But I think it is inconsistent with, for example, the current behaviour for other formats that contain time zone:
```haskell
parseTimeM True defaultTimeLocale (iso8601DateFormat $ Just "%H:%M:%S%Z") "2018-09-02T01:00:00+0500" :: Maybe LocalTime
-- => Just 2018-09-02 01:00:00
```

**Comment by waiting-for-dev** [comment]
If it matters, my use case is the following function, which doesn't work for `LocalTime` when the input format is unix seconds:

```haskell
-- | Parses a date guessing from a list of accepted formats. Right now
-- these are:
--   - iso8601: 2018-01-01
--   - iso8601 with time: 2018-01-01T12:35
--   - iso8601 with time and timezone: 2018-01-01T12:35+0100
--   - iso8601 with fractions of seconds: 2018-01-01T12:35.001000
--   - iso8601 with fractions of seconds and timezone:
--   2018-01-01T12:35.001000+0100
--   - rfc822: Mon, 01 Jan 2018 12:35:00 +0100
--   - epoch: 1514810100
parseTimeGuess :: ParseTime t => Text -> Maybe t
parseTimeGuess string =
  let formats =
        [ iso8601DateFormat Nothing
        , iso8601DateFormat $ Just "%H:%M:%S%Z"
        , iso8601DateFormat $ Just "%H:%M:%S%Q%Z"
        , rfc822DateFormat
        , "%s"
        ]
      results = parseTime' (T.unpack string) <$> formats
   in foldl1 (<|>) results
  where
    parseTime' = flip $ parseTimeM True defaultTimeLocale
```

**Comment by taphu** [comment]
> No, this is correct behaviour. `%s` only works for `UTCTime` and `ZonedTime`. It's documented. http://hackage.haskell.org/package/time-1.9.2/docs/Data-Time-Format.html

I am curious to understand why this intended behavior is considered correct. The documentation is a little short on any context other than the bare fact that this is how `%s` behaves.

**Comment by AshleyYakeley** [comment]
`%s` represents UTC time, so it can only be used with types that can represent UTC time, that is, `UTCTime` and `ZonedTime`.

For example, `%s`=0 represents midnight at the beginning of 1970-01-01 UTC. There's no particular `LocalTime` that represents that time.

**Comment by waiting-for-dev** [comment]
However, `2018-09-02T01:00:00+0000` also represents UTC time and can be parsed to `LocalTime`, isn't it?

**Comment by AshleyYakeley** [comment]
`2018-09-02T01:00:00+0000` has enough information to specify a `UTCTime`, a `LocalTime`, or a `ZonedTime`.

**Comment by taphu** [comment]
Ok. That makes sense. I guess the important part is that the meaning of the Unix timestamp is the number of seconds since `01 January 1970` **UTC**, as opposed to `01 January 1970` in whatever you local timezone happens to be (which I don't think could even be a coherent definition, given daylight saving).

**Comment by AshleyYakeley** [comment]
Yes, this is the rationale.

**Comment by waiting-for-dev** [comment]
Sorry, but I still don't get the difference.

Right, the format in `2018-09-02T01:00:00+0000` can be used to represent time in UTC or in another time zone, but when you convert to `LocalTime` you just loose that information:

```haskell
parseTimeM True defaultTimeLocale (iso8601DateFormat $ Just "%H:%M:%S%Z") "2018-09-02T01:00:00+0000" :: Maybe LocalTime
-- Just 2018-09-02 01:00:00
follow> parseTimeM True defaultTimeLocale (iso8601DateFormat $ Just "%H:%M:%S%Z") "2018-09-02T01:00:00+0600" :: Maybe LocalTime
--Just 2018-09-02 01:00:00
```

I think it is not consitent with `%s`. It also contains UTC time zone (ok, it can't represent any other time zone, but it doesn't matter), so to be consistent with the previous behaviour it just should forget the time zone.

If I don't understand wrong, `LocalTime` is just a day and time aggregate, which doesn't know about time zones. So I think it make sense it just misses time zone information when converting from one format with time zone.

**Comment by AshleyYakeley** [comment]
Times specified by `%s` are absolute times (i.e. `UTCTime`), they don't specify any time zone. They cannot be converted to `LocalTime` without providing a time zone.

If you want to convert a time specified by `%s` to a `LocalTime`, you must explicitly provide the time zone (e.g. by parsing it as a `UTCTime` and then using `utcToLocalTime` with a `TimeZone`).

**Comment by waiting-for-dev** [comment]
Thanks, now it is more clear. However, I still think that a straighforward conversion forgetting about leap seconds and everything is still possible and it makes sense. Even more considering that a `LocalTime` is more related to how humans understand time that to actual time values.
