### ISSUE TITLE
Provide simple functions to convert to concrete times since epoch

### ISSUE THREAD

**Issue by nh2** [haskell/time#106]
On StackOverflow I'm encountering lots of wrong answers on how to turn a given `UTCTime` into a given amount of milli-, micro- or nano-seconds.

* https://stackoverflow.com/questions/13482958/haskell-convert-utctime-to-seconds-and-milliseconds
* https://stackoverflow.com/questions/17909770/get-time-as-int#comment92245535_34537805 (note how using `read` is the most upvoted and accepted answer!

Further, using `realToFrac . utcTimeToPOSIXSeconds` and the implementation detail of how many digits the resulting number has is complicated and easy to get wrong. People always ask me about it, and I myself have to look it up every time.

Can we have some simple functions,

```
utcEpochMillis :: UTCTime -> Integer
utcEpochMicros :: UTCTime -> Integer
utcEpochNanos :: UTCTime -> Integer
```

or equivalent fixed-sized integer variants that guarantee the desired output and are really easy to use?

Alternatively, directly copy-pastable instructions on how to do it directly in the docs of `UTCTime`?

Thanks!

**Comment by AshleyYakeley** [comment]
I dislike these, as they specialise on the POSIX epoch as a zero time, and also on particular time units.

**Comment by AshleyYakeley** [comment]
Correct way is actually `nominalDiffTimeToSeconds . utcTimeToPOSIXSeconds` which has type `UTCTime -> Pico`.

**Comment by nh2** [comment]
OK, so you'd recommend the following for people looking for nanos since epoch (requires `time >= 1.9.1`)?

```haskell
#!/usr/bin/env stack
-- stack --install-ghc --resolver lts-11.22 runghc --package time-1.9.1

{-# OPTIONS_GHC -Wall #-}

import           Data.Time.Clock (UTCTime, getCurrentTime, nominalDiffTimeToSeconds)
import           Data.Time.Clock.POSIX (utcTimeToPOSIXSeconds)
import           Data.Int (Int64)

nanosSinceEpoch :: UTCTime -> Int64
nanosSinceEpoch =
  floor . (1e9 *) . nominalDiffTimeToSeconds . utcTimeToPOSIXSeconds

main :: IO ()
main = do
  u <- getCurrentTime :: IO UTCTime
  print (nanosSinceEpoch u)
```

**Comment by AshleyYakeley** [comment]
Yes, this looks good to me.
* `utcTimeToPOSIXSeconds` gets time since epoch
* `nominalDiffTimeToSeconds` converts that time to seconds
* `(1e9 *)` converts seconds to nanoseconds
* `floor` converts nanoseconds to a whole number

**Comment by nh2** [comment]
Great, I made PR #108 to mention this common use case directly in the docs.
