### ISSUE TITLE
Why doesn't ghc ship time 1.9.x?

### ISSUE THREAD

**Issue by peti** [haskell/time#107]
I was surprised to find that even recent ghc releases such as 8.6.2 still ship time version 1.8.x. Is anyone aware of the reason why they haven't updated their copy yet?

**Comment by AshleyYakeley** [comment]
This was due to a miscommunication. You can safely update locally to use time-1.9.2 with GHC 8.6.

GHC 8.8 will ship with the latest time library.

**Comment by peti** [comment]
It doesn't seem like it's that easy. I added a `time > 1.9` constraint to my project's Cabal file, but now I can no longer build it:

~~~
$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: distribution-suse-0 (user goal)
[__1] trying: vector-0.12.0.1/installed-BKW... (dependency of
distribution-suse)
[__2] trying: primitive-0.6.4.0/installed-1mv... (dependency of vector)
[__3] trying: transformers-0.5.5.0/installed-0.5... (dependency of primitive)
[__4] trying: time-1.8.0.2/installed-1.8... (dependency of distribution-suse)
[__5] trying: base-4.12.0.0/installed-4.1... (dependency of distribution-suse)
[__6] next goal: emu-incident-report (user goal)
[__6] rejecting: emu-incident-report-0 (conflict:
time==1.8.0.2/installed-1.8..., emu-incident-report => time>1.9)
[__6] fail (backjumping, conflict set: emu-incident-report, time)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: unix, base, process, template-haskell,
optparse-applicative, time, primitive, transformers, vector,
data-lens-template, emu-incident-report, distribution-suse
~~~

There appears to be an implicit `time installed` constraint somewhere? Maybe that comes from `base`? I can work around this by specifying `--allow-newer`, of course, but this is getting unpleasant fast.

**Comment by AshleyYakeley** [comment]
Ah, you'll need to drop upper-bounds checking. Try `--allow-newer`.

**Comment by AshleyYakeley** [comment]
A number of packages set `time < 1.9` and only update that when a new `time` comes out, but AFAIK there should be no compatibility problem.

**Comment by AshleyYakeley** [comment]
Sorry, this isn't ideal but it's the best that can be done for the time being.

**Comment by peti** [comment]
OK, thank you very much for your efforts.
