### ISSUE TITLE
Why `nominalDiffTimeToSeconds` doesn't return Int?

### ISSUE THREAD

**Issue by wizzup** [haskell/time#110]
I am new to the library, sorry if I miss some importance concept.

The function name `nominalDiffTimeToSeconds` imply it will return multiples of `second` which doesn't seem divisible (unless you speaking about `millisecond or microseconds` but that should be sepeate functions of their own)

**Comment by AshleyYakeley** [comment]
So the idea is that it will convert 3.2s to 3.2 (for example). If you also want to rounding or truncation or whatever, that's a separate step.

**Comment by wizzup** [comment]
I have no problem getting the unit I want, just want to say the function name can be misunderstanding, (maybe it is just only me)
