### ISSUE TITLE
Instance Documentation Links Broken

### ISSUE THREAD

**Issue by awhtayler** [haskell/time#114]
Eg. see http://hackage.haskell.org/package/time-1.9.2/docs/Data-Time-LocalTime.html , FormatTime instance for TimeZone points to http://hackage.haskell.org/package/time-1.9.2/docs/Data-Time-Format-Format-Instances.html which doesn't exist rather than directly to the source http://hackage.haskell.org/package/time-1.9.2/docs/src/Data.Time.Format.Format.Instances.html 

Likewise for NFData instance pointing to Data.Time.LocalTime.Internal.TimeZone , I guess anywhere where there isn't an associated doc page then this happens.

**Comment by AshleyYakeley** [comment]
The instance is defined in a private module, so there's no haddock page for it.

I suppose ideally there would not be a link?

**Comment by awhtayler** [comment]
Imo ideal would be linking directly to the source code if there's no haddock page. In one way broken links > no links because at least it told me where to look! though initially I assumed they were from an older version.

**Comment by AshleyYakeley** [comment]
That text is autogenerated by Haddock. I don't think I can change it.

**Comment by awhtayler** [comment]
I don't really know how Haddock works but clearly auto-generated broken links is not a good thing; if it can't be fixed manually is it worth submitting an issue to Haddock instead?

**Comment by AshleyYakeley** [comment]
Possibly? In any case, this does not seem to be anything that can be fixed in the time package.
