### ISSUE TITLE
Error parsing the T in ISO 8610 dates

### ISSUE THREAD

**Issue by aztek** [haskell/time#115]
I am using `time-1.9.3` and I want to parse the date `2011-11-19T18:28:52Z` using `read`. It looks like `read` can not handle the `T` character:

```
λ: read "2011-11-19T18:28:52Z" :: UTCTime
*** Exception: Prelude.read: no parse

λ: read "2011-11-19 18:28:52Z" :: UTCTime
1970-01-01 00:00:00 UTC
```

Am I not invoking the ISO 8610 parser from importing `Data.Time` or is this a bug?

**Comment by AshleyYakeley** [comment]
If you to parse specifically in ISO 8601 format, you should look at `Data.Time.Format.ISO8601`. In this case you can use `iso8601ParseM`, which will parse to `UTCTime` in ISO 8601:2004(E) sec. 4.3.2 extended format.
