### ISSUE TITLE
Aliases for timeToTimeOfDay and timeOfDayToTime

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/time#117]
Currently the API has

* `timeToTimeOfDay :: DiffTime -> TimeOfDay` (Get the time of day given a time since midnight. Time more than 24h will be converted to leap-seconds), and
* `timeOfDayToTime :: TimeOfDay -> DiffTime` (Get the time since midnight for a given time of day.)

I think these would be clearer written

* `pastMidnight  :: DiffTime -> TimeOfDay`, and
* `sinceMidnight :: TimeOfDay -> DiffTime`

What do you think?  Could these be added as aliases?

**Comment by AshleyYakeley** [comment]
Fixed for 1.10.

**Comment by tomjaguarpaw** [comment]
Thanks!
