### ISSUE TITLE
Add YearMonth and YearQuarter

### ISSUE THREAD

**Issue by phadej** [haskell/time#118]
I have a (non-released) package doing that in, haddocks (with sources) are at https://oleg.fi/haddocks/months/ I'd like the types to be migrated to `time`.

Compare to Java's
- https://docs.oracle.com/javase/8/docs/api/java/time/YearMonth.html
- https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/YearQuarter.html

I think `YearMonth` should be simple addition, even `FormatTime` and `ParseTime` instances would work nicely (when written). `YearQuarter` is trickier as there isn't quarter-format character, and it's tricky with fiscal years not-starting with January. Yet, I'm not too worried given the `threeten` picked the same naming and behaviour (you have to believe me, I first written the code, and then looked for prior art!)

The motivation is reversing dependencies, `months` is good for my use case, but it's batteries included - having all the possible instances from quite heavy packages.

EDIT: I'll be happy to write the modules for `time`, if the idea is welcome in general.

**Comment by AshleyYakeley** [comment]
Can't you just use `(Integer,Int)` for year-month? It already has correct `Eq` and `Ord` instances.

I'm trying to avoid proliferating types. There's no "month-day" or "day of year" type, for example, other than `Int`.

**Comment by phadej** [comment]
I cannot, I need those for their instances. Also Month is better than Int, IMO, cf Weekday

**Comment by mpilgrem** [comment]
I found myself looking for an existing `YearMonth` type on Hackage because I was using a JSON web service that delivered monthly data using the ISO 8601 "YYYY-MM" format to identify the months. Packages `time` and `attoparsec-iso8601` handled `Day` but not `YearMonth`.

**Comment by NorfairKing** [comment]
> Can't you just use (Integer,Int) for year-month?

These are not safe either.

**Comment by AshleyYakeley** [comment]
Would probably do something like this:
```
newtype AbsoluteMonth = MkAbsoluteMonth Integer -- year*12 + (month - 1)
  deriving (Eq,Ord)
absoluteAddMonths :: Integer -> AbsoluteMonth -> AbsoluteMonth
absoluteDiffMonths :: AbsoluteMonth -> AbsoluteMonth -> Integer

newtype AbsoluteYearQuarter = MkAbsoluteYearQuarter Integer -- year*4 + (quarter - 1)
  deriving (Eq,Ord)
absoluteAddYearQuarters :: Integer -> AbsoluteYearQuarter -> AbsoluteYearQuarter
absoluteDiffYearQuarters :: AbsoluteYearQuarter -> AbsoluteYearQuarter -> Integer
```

While I would prefer not to create a new `MonthOfYear` type (see #134), since we already use `Int` for month-of-year, we could have a new `QuarterOfYear` type.

**Comment by NorfairKing** [comment]
@AshleyYakeley I'd rather call it `Month` and `Quarter` instead of `AbsoluteMonth` and `AbsoluteYearQuarter`, but that's a minor issue. SGTM.

**Comment by dbaynard** [comment]
I'd like to see the `QuarterOfYear` type. I deal with quarters which end/begin on the last Friday of the three month period; I don't think `time` should directly support this but I should be able to use whatever primitives time provides this case.

Also,

> newtype AbsoluteMonth = MkAbsoluteMonth Integer -- year*12 + (month - 1)

Would `year - 1` make more sense? I'm not certain what expectations are around handling year 0 but from my reading we probably want the enumeration to start with 0 at 0001-01-01. Even `year - 1970` might be a better choice.

**Comment by AshleyYakeley** [comment]
Is there any kind of standard, canonical, well-known, or commonly used mapping between absolute months and integers? I looked but I couldn't find one.

If there isn't one, users should generally avoid using the `MkAbsoluteMonth` constructor, though the time library should still expose it.

**Comment by NorfairKing** [comment]
Just to be clear, `QuarterOfYear` would just be `Q1 | Q2 | Q3 | Q4`, right?

**Comment by AshleyYakeley** [comment]
Done.

**Comment by phadej** [comment]
@AshleyYakeley thanks!

**Comment by NorfairKing** [comment]
@AshleyYakeley Thanks!
