### ISSUE TITLE
Handling of padding width on parsing 

### ISSUE THREAD

**Issue by GambolingPangolin** [haskell/time#121]
Let me start with an example:

```
ghci> now <- localTimeOfDay . zonedTimeToLocalTime <$> getZonedTime
gchi> parseTimeM True defaultTimeLocale "%_3H" $ formatTime True "%_3H" now
Nothing
```

In this case the parse should succeed and the result should be `now`, rounded down to the nearest hour.  For other format string and time value pairs, what should happen depends on the specifics.

The reason for the parse failure appears to be in `Data.Time.Parse.Class`.   [`parseSpecifiers`][1] does not recognize padding widths on analyzing the format string and hands off the width to [`parseTimeSpecifiers`][2], which typically fails.

**Edit:** fixed mistake in example

[1]: http://hackage.haskell.org/package/time-1.9.3/docs/src/Data.Time.Format.Parse.Class.html#parseSpecifiers
[2]: http://hackage.haskell.org/package/time-1.9.3/docs/src/Data.Time.Format.Parse.Class.html#parseTimeSpecifier

**Comment by AshleyYakeley** [comment]
This behaviour is as documented: ["padding widths are not supported"](https://hackage.haskell.org/package/time-1.9.3/docs/Data-Time-Format.html#g:2). If you parse with `%_H` rather than `%_3H`, the example succeeds.

There doesn't seem to be a good reason for padding widths when parsing. The parser should accept the string if it can regardless of width.

**Comment by GambolingPangolin** [comment]
My bad; I missed that bit of the documentation!  Currently padding widths are not supported in the sense that parses always fail if the format string contains a padding width.  Are you suggesting the variation where the parsing logic ignores padding widths?  For example, under that scheme:
```haskell
parserA = parseTimeM True defaultTimeLocale "%H%_3M%S"
parserB = parseTimeM True defaultTimeLocale "%H%_M%S" -- identical behavior to parserA
```

**Comment by AshleyYakeley** [comment]
Actually I believe the current behaviour is fine. `parserB` should succeed regardless of the number of characters used for the minutes. `parserA` should always fail, as `%_3M` is an invalid code for parsing.
