### ISSUE TITLE
documentation: clarify that `fromEnum :: NominalDiffTime -> Int` doesn't return seconds

### ISSUE THREAD

**Issue by schmittlauch** [haskell/time#129]
The documentation writes about `NominalDiffTime`:

> Conversion functions will treat it as seconds. For example, (0.010 :: NominalDiffTime) corresponds to 10 milliseconds.

Converting a `NominalDiffTime` the other way around to Int by `fromEnum`, the internal representation of picoseconds is returned, resulting in a value that is 10^12 times larger than a second.

While I can see why it behaves like that and the newly introduced `nominalDiffTimeToSeconds` might help catching most instances of this error, I still think that the documentation is misleading. I am probably not the first person categorising `fromEnum` as a **conversion function** and thus expecting it to return seconds.

I am willing to create a PR with doc clarifications, but before that I'd like to know what the maintainer sees as *conversion functions*, whether `fromEnum` is one and if not, why not.

**Comment by AshleyYakeley** [comment]
`NominalDiffTime` is an instance of various numeric classes, so I actually meant `fromInteger`, `realToFrac` and the like.

By contrast `fromEnum` considers the type as an enumeration, with successor and predecessor functions.
For example, `succ (0.010 :: NominalDiffTime)` will give the next `NominalDiffTime`, which is `0.010000000001s`. This seems like appropriate behaviour to me.

**Comment by AshleyYakeley** [comment]
Done.
