### ISSUE TITLE
RFC 5545 week dates with a custom week start.

### ISSUE THREAD

**Issue by NorfairKing** [haskell/time#133]
RFC 5545 defines a week in https://tools.ietf.org/html/rfc5545#section-3.3.10 as

>  A week is defined as a seven day period, starting on the day of the week defined to be the week start (see WKST).  Week number one of the calendar year is the first week that contains at least four (4) days in that calendar year.  

I defined code to compute from and to those here:

https://github.com/NorfairKing/smos/blob/fe3acdb89b73e412b91f69f5a17c3cec839775d9/smos-calendar-import/src/Smos/Calendar/Import/RecurrenceRule.hs#L1111-L1131

Would you be interested in upstreaming this code?

The code isn't perfect yet, but I already have a bunch of test cases for it: https://github.com/NorfairKing/smos/blob/fe3acdb89b73e412b91f69f5a17c3cec839775d9/smos-calendar-import/test/Smos/Calendar/Import/RecurrenceRule/WeeklySpec.hs#L17-L108

**Comment by AshleyYakeley** [comment]
Isn't this the same as [this](http://hackage.haskell.org/package/time-1.10/docs/Data-Time-Calendar-WeekDate.html)?

> Convert to ISO 8601 Week Date format. First element of result is year, second week number (1-53), third day of week (1 for Monday to 7 for Sunday). Note that "Week" years are not quite the same as Gregorian years, as the first day of the year is always a Monday. The first week of a year is the first week to contain at least four days in the corresponding Gregorian year.

**Comment by NorfairKing** [comment]
This is the difference:

> as the first day of the year is always a Monday

RFC 5545 does not specify this limitation.

**Comment by AshleyYakeley** [comment]
So it's a generalisation, for any given week start?

**Comment by NorfairKing** [comment]
Yes I think that's right.

**Comment by NorfairKing** [comment]
@AshleyYakeley You're the best!
