### ISSUE TITLE
Test suite fails on WSL2

### ISSUE THREAD

**Issue by mulderr** [haskell/time#136]
Output from `stack test`:
```
time> test (suite: test-main, args: --hide-successes)

Time
  Clock
    resolution
      getCurrentTime:                                                             FAIL (0.16s)
        test/main/Test/Clock/Resolution.hs:55:
        resolution
        expected: 0.000000001s
         but got: 0.0000001s
      taiClock:                                                                   FAIL (0.14s)
        test/main/Test/Clock/Resolution.hs:55:
        resolution
        expected: 0.000000001s
         but got: 0.0000001s
 
2 out of 26365 tests failed (26.63s)
```

`getTime_resolution` is defined to be 100ns for Windows and 1ns otherwise. However, at least on my machine, on Ubuntu under WSL2, I seem to be getting only 100ns resolution - as if running on Windows. I've also seen the same error for `time-compat` while building with `nix`.

Details:
* Windows version: Microsoft Windows [Version 10.0.19041.508]
* WSL2
* Ubuntu 20.04
* stack 2.3.3

How to reproduce:
1. Install WSL2 on Windows 10: https://docs.microsoft.com/en-us/windows/wsl/install-win10
2. Install Ubuntu 20.04 from Microsoft Store and launch it
3. sudo apt install haskell-stack && sudo stack upgarde
4. git clone https://github.com/haskell/time
5. cd time
6. stack setup
7. stack test

**Comment by AshleyYakeley** [comment]
Was your Windows installed directly on the physical computer, or is this a VM? I've seen this issue in VMs.

**Comment by mulderr** [comment]
Windows is installed directly on hardware but WSL2 is basically a simplified/optimized version of Hyper-V. So this could be exactly what you were seeing before.

I'm thinking, should we try to detect WSL in the configure script and have another case for `getTime_resolution`?

**Comment by AshleyYakeley** [comment]
On Windows, it's possible to build Haskell programs for either Windows directly, or as Linux binaries that can run on WSL, is that correct?

**Comment by mulderr** [comment]
Not quite. I'm new to WSL myself but turns out that just enabling WSL2 on Windows 10, which btw requires a reboot, silently installs a stripped down Hyper-V (bare metal hypervisor) that then runs both your main Windows OS, as a privileged VM with hardware passthrough, and any Linuxes you may want as separate VMs.

So I guess one may think of WSL2 as Linux VMs with Microsoft provided kernels running on top of Hyper-V. This is probably gross oversimplification and there may be important details that I missed but that seem to be the gist of it. I'm not sure if the timer resolution issue is coming from Hyper-V itself or maybe the customized kernel configuration. Still investigating.

First I'm going to try to reproduce on another machine that I just got a hold of.

**Comment by AshleyYakeley** [comment]
Could you try switching to the ghc branch? The master branch is generally in flux.

`git checkout ghc`

**Comment by mulderr** [comment]
No change on the ghc branch. Checked on both machines.

For comparison, also used the same method on a NixOS VM running on VMware ESX 6.x and it does *not* exhibit any issues. All tests pass.

It remains to be seen if it's WSL2 specific or Hyper-V issue in general. Since you say you've seen this before on VMs it could as well be Hyper-V in general but I don't have access to a Hyper-V environment to test.

**Comment by mulderr** [comment]
Potentially related:
https://github.com/microsoft/WSL/issues/77

**Comment by mulderr** [comment]
Confirmed the above with a bit of C. It sure is constant 10MHz but at the same time `clock_getres` is lying about the resolution:
* `clock_getres` reports resolution of 1ns
* `clock_gettime` always returns tv_nsec divisible by 100

**Comment by mulderr** [comment]
Right, so to wrap this up. Looks to me like an upstream issue between Hyper-V and Linux kernel.

First time reading Hyper-V specs is though but various parts of the [Hypervisor Top-Level Functional Specification](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/tlfs) mention 100ns steps. Notably section 12.3 Partition Reference Time Enlightenment. So I hope I am interpreting this correctly that the 100ns TSC realtime clock resolution is a Hyper-V thing and is "normal".

What doesn't seem normal is that `clock_getres` returns 1ns even on a kernel running on Hyper-V and using TSC page. I *think* it should say 100ns to be consistent but I'm not sure. Think the place to ask is Microsoft/WSL so I will do just that.

**Comment by mulderr** [comment]
https://github.com/microsoft/WSL/issues/6029

**Comment by AshleyYakeley** [comment]
OK. I'm going to try to reproduce this on my machines. But if it's a defect in the `clock_getres` C call, it's probably best not to try to work around it in the Haskell time library.

**Comment by AshleyYakeley** [comment]
Unsurprisingly, I get the same problem with WSL2 on my Windows machine. Probably the best thing to do is just make a note of it in the haddock documentation, rather than try to work around it.

**Comment by AshleyYakeley** [comment]
Done.

**Comment by simonpj** [comment]
I was about to update to WSL2 from WSL1.  Is that a good thing to do, do you think?

**Comment by AshleyYakeley** [comment]
Depends on the purpose?

As far as the time library is concerned, this particular issue will cause a test failure on WSL2. It won't prevent the time library from building.

**Comment by mulderr** [comment]
In general, apart from test suite failures on `time` and `time-compat` I am not seeing any issues so far but I've started using WSL/WSL2 only this weekend. So cannot say much and nothing in particular about upgrade from WSL1. YMMV.

For anyone using Nix, you may want to make sure that both `time` and `time-compat` are already in the cache or for example build them on a different machine and nix-copy-closure. Otherwise you will have to manually disable tests which will change the hash which may translate to lots of compile time.

**Comment by Tritlo** [comment]
Note: if you are hitting this error while using `ghc.nix`, you can circumvent it by adding cachix (`nix-env -iA nixpkgs.cachix`) and then   write `cachix use ghc-nix` to get the pre-built cabal (and thus avoding having to build `time` and `time-compat`).

**Comment by AlexKnauth** [comment]
I am also trying to use `time-compat` via Nix on WSL, and I am running into the same clock resolution test failures.

I've tried building both normally and with `cachix use ghc-nix`, and neither has worked so far.

What is the recommended way of working around this issue? The documentation says
> On UNIX systems this uses `clock_getres`, which may be wrong on WSL2.

But it doesn't say how to correct for it.

**Comment by mulderr** [comment]
Some options:
* override `time-compat` in `shell.nix`, `flake.nix` etc. and disable tests ex. using `dontCheck` from `...haskell.lib`
* build on another machine and `nix-copy-closure` or put it in a private/company cache if you have one
* make sure you hit cache.nixos.org

The last one usually works for me - I can mostly get away with pinning nixpkgs to a hash from the current stable channel.
