### ISSUE TITLE
Add Enum Month and Quarter

### ISSUE THREAD

**Issue by phadej** [haskell/time#141]
I think GND instance should be fine?

EDIT: and while we on it, also `Ix` and `NFData`.

**Comment by AshleyYakeley** [comment]
oops

**Comment by phadej** [comment]
I don't think that have to be 1.12, It can be 1.11.1 as well :)

**Comment by AshleyYakeley** [comment]
You're in luck, I have to do 1.11.1 for #143 anyway. I think GND may not be `SAFE` though.

**Comment by AshleyYakeley** [comment]
OK this is done.
