### ISSUE TITLE
Add a helper for converting a DiffTime to integral picoseconds

### ISSUE THREAD

**Issue by jmillikin** [haskell/time#15]
The `picosecondsToDiffTime :: Integer -> DiffTime` function provides full-precision conversion of integral picoseconds to a DiffTime, but there is no reverse. This makes it difficult to use DiffTime in some code because the user has to go through `toRational` and then deconstruct the Rational to recover the original input value.

I propose a `diffTimeToPicoseconds :: DiffTime -> Integer` function be added.

**Comment by AshleyYakeley** [comment]
Added.
