### ISSUE TITLE
Possible inclusion of other time locales

### ISSUE THREAD

**Issue by tchoutri** [haskell/time#157]
Hi! Would the maintainers be open to the inclusion of other time locales? I'm thinking of the French one, for instance.

**Comment by AshleyYakeley** [comment]
Possibly? Where would the information come from? If it's available from the TZ database, then it might be possible after #89.

**Comment by AshleyYakeley** [comment]
The time package does not itself contain country-specific information, because it keeps changing. #89 is to provide access to the TZ database, which may have this information.
