### ISSUE TITLE
CLOCK_MONOTIME is not available

### ISSUE THREAD

**Issue by uebayasi** [haskell/time#159]
It is useful to measure computation times etc.

**Comment by AshleyYakeley** [comment]
Do you mean CLOCK_MONOTONIC? Is there an equivalent clock on Windows?

**Comment by AshleyYakeley** [comment]
The clock package [provides this](http://hackage.haskell.org/package/clock-0.8.2/docs/System-Clock.html). It's probably best if the time package doesn't duplicate this work.
