### ISSUE TITLE
According to ISO 8601:2004 § 4.3.2 something like "1985-04-12T10:15:30+04" is valid.

### ISSUE THREAD

**Issue by alaendle** [haskell/time#184]
However it seems that time zones could just be parsed in the format "±hh[:]mm".

Not sure if this counts as a bug or if my understanding of the iso norm is wrong.
I just encountered this divergence while using `iso8601ParseM` to parse a similar string.

https://github.com/haskell/time/blob/caa9ecb3a79cf4d952d9c357ed5aa428aa4adb26/lib/Data/Time/Format/Parse/Instances.hs#L359-L362

**Comment by AshleyYakeley** [comment]
Fixed.
