### ISSUE TITLE
Supporting decimal fractions on values other than seconds

### ISSUE THREAD

**Issue by giulioforesto** [haskell/time#213]
## Expected behavior

The [standard](https://www.loc.gov/standards/datetime/iso-tc154-wg5_n0038_iso_wd_8601-1_2016-02-16.pdf) says: "_If necessary for a particular application, the lowest order component**s** may have a decimal fraction._" (§4.4.3.2) The plural suggests that it's not the lowest order component in absolute (if so, why wouldn't they have written just "seconds"?), but rather the lowest that is used in the time interval representation we're talking about. This is also what the definition of "decimal representation" stands (§2.3.6): "_decimal representation: expansion of a representation by addition of a decimal fraction to the lowest order component of the expression_"

So the following should be valid:
- `P1.5Y`
- `PT0.2H`

But the following shouldn't:
- `P1.5YT1D`
- `PT0.2H6S`

## Current behavior
Currently, it seems that decimal representation is allowed only on seconds:
```
ghci> import Data.Time.Format.ISO8601
ghci> iso8601ParseM "PT1H" :: Maybe CalendarDiffTime 
Just P0MT3600S
ghci> iso8601ParseM "PT1.5H" :: Maybe CalendarDiffTime 
Nothing
ghci> iso8601ParseM "PT1S" :: Maybe CalendarDiffTime 
Just P0MT1S
ghci> iso8601ParseM "PT1.5S" :: Maybe CalendarDiffTime 
Just P0MT1.5S
ghci> iso8601ParseM "P1Y" :: Maybe CalendarDiffTime 
Just P12MT0S
ghci> iso8601ParseM "PT1.5Y" :: Maybe CalendarDiffTime 
Nothing
```

**Comment by AshleyYakeley** [comment]
Fractional hours and minutes should be OK. But we run into problems with fractional years and months, as they can't be directly represented in `CalendarDiffTime`. Also, if I fix #210, fractional days become tricky.

**Comment by AshleyYakeley** [comment]
How long is half a month?

**Comment by dcastro** [comment]
For what it's worth, `java.time` and joda-time don't seem to handle this either: https://scastie.scala-lang.org/dcastro/vB4apOIwQdOEl6rORycOWA/89

**Comment by AshleyYakeley** [comment]
I think this handling of half a month is counter-intuitive, and it's better not to support it.
