### ISSUE TITLE
DiffTime does not have ParseTime or FormatTime instances

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/time#22]
Is there a reason that `DiffTime` does not have `ParseTime` or `FormatTime` instances?

**Comment by tomjaguarpaw** [comment]
Inspired by this question: http://stackoverflow.com/questions/27720867/haskell-time-type-holding-milliseconds

**Comment by gibiansky** [comment]
This would be nice to have.

**Comment by AshleyYakeley** [comment]
Hmm, maybe something like:

total weeks: %w
days of week: %D
total days: %d
total hours: %h
hours of day: %H
total minutes: %m
minutes of hour: %M
total seconds: %s
seconds of minute: %S
picosecond of second: %q
fraction of second: %Q

**Comment by AshleyYakeley** [comment]
Should apply to `DiffTime`, `NominalDiffTime`, `CalendarDiffDays`, `CalendarDiffTime`.

Probably capital for total and lower case for relative would make more sense:

total years: %Y
total months: %B
months of year: %b
total weeks: %W
total days: %D
days of week: %d
total hours: %H
hours of day: %h
total minutes: %M
minutes of hour: %m
total seconds: %S
seconds of minute: %s
picosecond of second: %q (same as time types)
fraction of second: %Q (same as time types)

**Comment by AshleyYakeley** [comment]
OK, done.
