### ISSUE TITLE
time-1.5.0.1 test suite doesn't compile

### ISSUE THREAD

**Issue by peti** [haskell/time#23]
I get the following error:

    Preprocessing test suite 'tests' for time-1.5.0.1...

    test/Test/Tests.hs:16:8:
        Could not find module ‘Test.TestTimeZone’
        Use -v to see a list of the files searched for.

I suppose this means that there's a module missing from the Cabal file (and hence the release tarball).

**Comment by AshleyYakeley** [comment]
Fixed.

**Comment by peti** [comment]
Will you release a new version?
