### ISSUE TITLE
Data.Time.LocalTime.TimeZone is not a timezone but a timezone offset

### ISSUE THREAD

**Issue by NorfairKing** [haskell/time#231]
It would be great to:

1. Rename `TimeZone` to `TimeZoneOffset`
1. Have a proper `TimeZone`
1. Have an api like `TimeZone -> LocalTime -> TimeZoneOffset`
1. Have an api like `LocalTime -> TimeZone -> [UTCTime]` (because each local time could reference 0, 1, or more utc times) and `UTCTime -> TimeZone -> LocalTime` (all without IO)

**Comment by AshleyYakeley** [comment]
So proper time-zone functionality is #89, to copy time-zone code from the timezone-series & timezone-olson packages. This would be time version 2.0.

> Rename `TimeZone` to `TimeZoneOffset`

This may or may not be worth doing. It's certainly a regret of mine, see [here](https://github.com/haskell/time/issues/16#issuecomment-66903808). But there are also [other issues](https://github.com/haskell/time/issues/174#issuecomment-880510840) with the current `TimeZone` type.

> `localTimeToUTC` is nice, but how is a user supposed to know which `TimeZone` (offset) is supposed to be used?

Currently the time library only knows about the configured time-zone. But to get the time zone offset for some particular time, you can use `getTimeZone`.

**Comment by AshleyYakeley** [comment]
Closing this as covered by #89.
