### ISSUE TITLE
Please provide documentation for Data.Time.Format.ISO8601

### ISSUE THREAD

**Issue by greydot** [haskell/time#238]
Hello!

Right now, it is completely unapparent how exactly this module should be used. Moreover, references to the ISO standard require the user to actually buy (or 🏴‍☠️ YAAARRRRRRR) the pdf, thus adding insult to injury.

Thank you!

**Comment by AshleyYakeley** [comment]
If you're not already working with ISO8601, and already have a copy of the standard, you don't need this module.

**Comment by greydot** [comment]
Unfortunately, I was pointed to it by the deprecation of https://hackage.haskell.org/package/time-1.12.2/docs/Data-Time-Format.html#v:iso8601DateFormat

**Comment by AshleyYakeley** [comment]
What format do you want?

**Comment by Profpatsch** [comment]
Seconded, I’d guess these all have a specific formatting string format, so giving an example in the docstring would be nice. The standard is not trivial to find nor understand unfortunately.

The implementations are not straightforward to understand so examples would help.

**Comment by AshleyYakeley** [comment]
Done.
