### ISSUE TITLE
Show instance for UTCTime is orphan

### ISSUE THREAD

**Issue by thomie** [haskell/time#25]
Simon Hengel in https://ghc.haskell.org/trac/ghc/ticket/9962 reports:

    Show instance for UTCTime is orphan

**Comment by jpvillaisaza** [comment]
@thomie There was discussion regarding that in issue https://github.com/haskell/time/issues/7. I'm not sure there was a solution.

**Comment by AshleyYakeley** [comment]
This is now fixed (though it's not obvious from haddock).
