### ISSUE TITLE
instance Random DiffTime

### ISSUE THREAD

**Issue by domenkozar** [haskell/time#250]
```haskell
instance Random DiffTime where
  random :: (RandomGen g) => g -> (DiffTime, g)
  random g =
    let (i, g') = random g
     in (picosecondsToDiffTime $ fromIntegral (i :: Integer), g')

  randomR :: RandomGen g => (DiffTime, DiffTime) -> g -> (DiffTime, g)
  randomR (a, b) g =
    let (i, g') = randomR (diffTimeToPicoseconds a, diffTimeToPicoseconds b) g
     in (picosecondsToDiffTime i, g')
```

**Comment by AshleyYakeley** [comment]
Hello, what's the issue here?

**Comment by domenkozar** [comment]
I'm in a need of such instance, so I figured I'd open an issue.

**Comment by AshleyYakeley** [comment]
That this should be added to the time library, is that correct?

This means taking a package dependency on `random` -- this might be OK but I need to check.

**Comment by AshleyYakeley** [comment]
Currently `random` depends on `splitmix` which depends on `time`, so the code can't go here. You'll have to put in the `random` package instead.

**Comment by Daniel-Diaz** [comment]
> Currently `random` depends on `splitmix` which depends on `time`, so the code can't go here. You'll have to put in the `random` package instead.

I believe this is only the case for non-ghc compilers. I think they are trying to avoid depending on time there.

**Comment by domenkozar** [comment]
https://github.com/haskell/random/issues/156

**Comment by Daniel-Diaz** [comment]
For reference:

https://github.com/haskellari/splitmix/blob/799700374ec214bf9a87ede1758ec73be676ed22/splitmix.cabal#L89-L108

**Comment by Bodigrim** [comment]
`time` is a GHC boot package and should not depend on non-boot packages (such as `random`).
