### ISSUE TITLE
Generic instance for DayOfWeek

### ISSUE THREAD

**Issue by NorfairKing** [haskell/time#252]
This would let me generate instances for type classes such as `GenValid`.

**Comment by AshleyYakeley** [comment]
OK, this might apply to other types too.

**Comment by NorfairKing** [comment]
> OK, this might apply to other types too.

Yes please!

**Comment by AshleyYakeley** [comment]
Relevant: #45, #99, #154

**Comment by AshleyYakeley** [comment]
Candidate types: `DayOfWeek`, `TimeOfDay`, `LocalTime`, `TimeZone`, `ZonedTime`, `CalendarDiffDays`, `CalendarDiffTime`.

**Comment by AshleyYakeley** [comment]
Hmm, might do all types with exposed constructors. Rationale in #45 not to do `UTCTime` was that the constructor was not exposed, but it is now.

**Comment by NorfairKing** [comment]
This would be a big win for my projects!
Note that this is a breaking change because many projects have orphan `Generic` instances for those types.

**Comment by NorfairKing** [comment]
@AshleyYakeley what are next steps?

**Comment by AshleyYakeley** [comment]
Done.
