### ISSUE TITLE
Week type

### ISSUE THREAD

**Issue by NorfairKing** [haskell/time#253]
It would be like Month but for absolute weeks, wrapping an integer.

**Comment by AshleyYakeley** [comment]
Starting which day?

**Comment by AshleyYakeley** [comment]
Well, what's your anticipated use for the type?

**Comment by AshleyYakeley** [comment]
Are there any standard or pre-existing numberings of weeks?

**Comment by NorfairKing** [comment]
I want to resolve `Monday` to "the soonest monday after today" or "the most recently past monday".
So I'd like to do something like:

```
resolve :: Day -> DayOfWeek -> Maybe Day
resolve today dow = 
  let (w, _) = toAbsoluteWeekDay today
      guessThisWeek = fromAbsoluteWeekDay (w, dow)
      guessNextWeek = fromAbsoluteWeekDay (succ w, dow)
  in if guessThisWeek > today then guessThisWeek else guessNextWeek
```

Currently I have this, which requires me to go via `Year` and `WeekOfYear` unlike I have to do when I want to do something similar for "the soonest 15th of the month after today":

```
nextDayOfWeek :: Day -> DayOfWeek -> Day
nextDayOfWeek = dayOfWeekHelper (\d current after -> if current > d then current else after) (addDays 7)
                       
previousDayOfWeek :: Day -> DayOfWeek -> Day
previousDayOfWeek = dayOfWeekHelper (\d current before -> if current < d then current else before) (addDays (-7))
                   
dayOfWeekHelper ::     
  (Day -> Day -> Day -> Day) ->
  (Day -> Day) ->            
  Day ->          
  DayOfWeek ->        
  Day
dayOfWeekHelper chooser changer day dow =
  let (y, woy, _) = toWeekDate day
      currentGuess = fromWeekDate y woy (fromEnum dow)
      otherGuess = changer currentGuess
   in chooser day currentGuess otherGuess
```

**Comment by NorfairKing** [comment]
> Are there any standard or pre-existing numberings of weeks?

Not that I can find here: https://en.wikipedia.org/wiki/ISO_week_date

In hindsight this would probably cause more confusion than it will help with, because of the "which start day?" problem.

**Comment by AshleyYakeley** [comment]
Can't you do this?

"the soonest monday after today" = `firstDayOfWeekOnAfter Monday $ succ today`

"the most recently past monday" = `firstDayOfWeekOnAfter Monday $ addDays (negate 7) today`

**Comment by NorfairKing** [comment]
Oh ehm, I didn't know about those functions
Whoops, and Thanks!

**Comment by BurningWitness** [comment]
Judging by the existence of `fromWeekDateValid`, an ISO week is already well-defined, so it would make sense to have it as a separate datatype, same as a month. The aforementioned [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date) Wikipedia page lists the two side by side.

Hard to say how useful it is, seems to be mostly [European business](https://history.stackexchange.com/a/51462)-related. I've used `Month` extensively to represent card expiry dates, and never seen them used outside of that context, so it feels like `Week` would occupy a similar niche.
