### ISSUE TITLE
Unexpected Julian dates

### ISSUE THREAD

**Issue by bens** [haskell/time#258]
```
ghci> Data.Time.Calendar.Julian.fromJulian 1900 1 1
1900-01-13
ghci> Data.Time.Calendar.Julian.fromJulian 2000 1 1
2000-01-14
ghci> Data.Time.Calendar.Julian.fromJulian 2000 1 2
2000-01-15
ghci> Data.Time.Calendar.Julian.fromJulian 2000 1 31
2000-02-13
```

These results seems unexpected to me, the parsed dates are shifted forward in time by thirteen days, usually, except the 1900 example is twelve days, I couldn't find any other examples of that from a quick try. Other years seem to be thirteen days as well.

**Comment by bens** [comment]
Ah, this is in time-1.12.2, I'll try in HEAD first.

**Comment by AshleyYakeley** [comment]
The Gregorian leap rule is every four years, except every 100 years, except every 400 years.

The Julian leap rule is every four years.

Thus, 1900 is a Julian leap year but not a Gregorian leap year. Your first example is before the Julian leap day of 1900, while the others are after.

**Comment by AshleyYakeley** [comment]
You can check [here](https://stevemorse.org/jcal/julian.html), but be sure to "Specify the month and day that the Julian year number was incremented" as January 1.

**Comment by bens** [comment]
Good grief, sorry for the noise, I was in a hurry and got Julian and Gregorian confused. Closing.
