### ISSUE TITLE
parseTime: Verify date's format AND validity

### ISSUE THREAD

**Issue by Ladi-Eladi** [haskell/time#27]
```parseTime :: ParseTime t => TimeLocale -> String -> String -> Maybe t```

parseTime checks the format of it's third argument (date string) using it's second (format string, for example 'YYYY-MM-DD'). However, it does not check the date's validity - instead it rounds to the closest valid date.

```
import System.Locale
import Data.Time
parseTime defaultTimeLocale "%Y-%m-%d" "2015-01-99" :: Maybe Day
```

```
Just 2015-01-31
```

What I'd like is to get a valid date, or error.

**Comment by AshleyYakeley** [comment]
Fixed in master.
