### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jonsterling** [haskell/time#29]
I am sorry if this is the wrong place to ask this—but I am curious if there is a changelog for this library available.

Thanks,
Jon

**Comment by fizruk** [comment]
Changelog would be really helpful, is it possible to compose one based on commit messages maybe?

**Comment by AshleyYakeley** [comment]
I added one, but it only has an entry for the latest 1.6.

**Comment by fizruk** [comment]
Well, that's a good start!

Now we need someone to step up and restore changes for the previous versions :)

I have had some issues recently due to changes in 1.4.0.1 (that only affected GHC 7.6 build though).
So I think changelog at least back to 1.4 would be nice to have.
