### ISSUE TITLE
Cleaner error reporting

### ISSUE THREAD

**Issue by k0ral** [haskell/time#31]
Looking at `lib/Data/Time/Format/Parse.hs`, I was surprised to see that the way parse errors are reported is through `fail` or `error`. Would you consider switching to something cleaner like `mzero` from `MonadPlus`, or `throwError` from `MonadError` ?

**Comment by AshleyYakeley** [comment]
`mzero` doesn't allow information about the error. `MonadError` is in `mtl`, which would mean adding it as a dependency, and I'm not sure it's a core library.

**Comment by k0ral** [comment]
If by core library you mean what is described in the paragraph 1.4 of [this article][1], then `mtl` is one of them.

[1]: https://wiki.haskell.org/Applications_and_libraries#Core_Libraries

**Comment by AshleyYakeley** [comment]
`time` is a boot library, while `mtl` is not: https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries/VersionHistory
