### ISSUE TITLE
getCurrentTime/getPOSIXTime do not support the full resolution offered by modern unices

### ISSUE THREAD

**Issue by redneb** [haskell/time#36]
`getCurrentTime` (which is defined in terms of `getPOSIXTime`) currently returns timestamps with microsecond resolution. Modern unices on the the other hand support nanosecond resolution timestamps via the call `clock_gettime(CLOCK_REALTIME)`. It would be nice if `time` supported that.

I would be happy to provide a pull request. It will require adding an hsc file.

**Comment by AshleyYakeley** [comment]
Do you happen to know if there's a Windows equivalent? That's not a blocker for doing it on Unix, but it would be nice to have too.

**Comment by redneb** [comment]
I am not an expert on Windows, but it does not appear that there is function with higher resolution than `GetSystemTimeAsFileTime` which is the one that we currently use.

**Comment by AshleyYakeley** [comment]
Merged, thanks!
