### ISSUE TITLE
Representing midnight as end of day.

### ISSUE THREAD

**Issue by ghost** [haskell/time#37]
The time library does not allow one to represent the end of a day. ISO-8601 time has a representation for this: 24:00:00 is a time representing midnight as the end of the day, rather than the beginning.

This has come up in some of the work I do professionally. I'd like to know what is possible, especially whether the time library can be enhanced to represent this time.

**Comment by AshleyYakeley** [comment]
Could you be more specific about which type, etc.?

**Comment by dharaj** [comment]
`TimeOfDay` would be the first type. Currently `todHour` has a range of 0-23. If it represented a time of day the way ISO-8601 specifies, a `TimeOfDay 24 0 0` would be valid and would represent midnight at the end of the day.

I don't know what kind of consequences this change would have for other types and functions. It's very possible that it would be more appropriate to have a separate ISO-8601 library. If you think that's the case, I can go my merry way. I would at least try to make such a library as similar to time and thyme as possible.

**Comment by AshleyYakeley** [comment]
Right now you can construct "TimeOfDay 24 0 0", and you can construct a LocalTime with it, but "makeTimeOfDayValid 24 0 0" will give Nothing.

I'd need to know what operations you'd expect to behave how.

**Comment by michelk** [comment]
Currently 
```haskell
(parseTimeM True defaultTimeLocale "%d.%m.%Y %H:%M" "01.01.2021 24:00") :: Maybe UTCTime
```
evaluates to `Nothing`

But it should be equal to 

```haskell
(parseTimeM True defaultTimeLocale "%d.%m.%Y %H:%M" "02.01.2021 00:00")
```

**Comment by AshleyYakeley** [comment]
Hmm, representing 24:00:00 might be a requirement for ISO 8601 formatting/parsing functions.

**Comment by AshleyYakeley** [comment]
OK, I've fixed this for ISO 8601 formatting, where it's required.

**Comment by AshleyYakeley** [comment]
Not sure what to do about `parseTimeM` etc.

**Comment by AshleyYakeley** [comment]
So the options are:
1. no change: if you want parsing to accept 24:00 then use the ISO 8601 functions
2. parsing always accepts 24:00 (changing existing behaviour)
3. a flag in `TimeLocale` that determines what to do

For 2 & 3, it's not clear what else should be allowed, e.g., [Japanese 30-hour clock](https://en.wikipedia.org/wiki/Date_and_time_notation_in_Japan), or possibly even other fields out of range rolling over.

**Comment by AshleyYakeley** [comment]
Going to stick with 1 for the time being.
