### ISSUE TITLE
Zulu suffix of UTC time

### ISSUE THREAD

**Issue by izgzhen** [haskell/time#39]
When I was doing some API calling with Haskell, I found that there is some different in UTC time representation between the Java/Python ones and the Haskell one using the `time` package. The Java/Python ones will also have a "Z" has suffix.

According to [wikipedia](https://en.wikipedia.org/wiki/Coordinated_Universal_Time#Time_zones), it seems like there is really some story involved.

However, I am not sure if it is really reasonable and worrying that there might be old dependency broken by adding a "Z".

**Comment by AshleyYakeley** [comment]
Could you be more specific? What behaviour are you seeing on the Haskell side?

**Comment by izgzhen** [comment]
For example, in Haskell I used:

```haskell
import Data.Time.Clock
import Data.Time.Format
main = do
    utcTime <- getCurrentTime
    let format = iso8601DateFormat (Just "%H:%M:%S")
    let time = formatTime defaultTimeLocale format utcTime
    print time
```

and the outputed time is like "2015-09-27T08:06:38".

But the IOS8601 seems saying that we should have a "Z" at the end.

> If the time is in UTC, add a Z directly after the time without a space. Z is the zone designator for the zero UTC offset. "09:30 UTC" is therefore represented as "09:30Z" or "0930Z". "14:45:15 UTC" would be "14:45:15Z" or "144515Z".
> UTC time is also known as 'Zulu' time, since 'Zulu' is the NATO phonetic alphabet word for 'Z'.
> -- wikipedia https://en.wikipedia.org/wiki/ISO_8601#UTC



And I doubt if the "Z" should be added automatically by library, or in my own specific `Maybe String` as argument of `iso8601DateFormat`
