### ISSUE TITLE
Any plans on exporting Generic instances?

### ISSUE THREAD

**Issue by mstksg** [haskell/time#45]
Hi all,

I hope to be able to use `UTCTime`'s (or `Day`'s and `DiffTime`s) in my data types and derive `Generic` for those types, but at the moment, this isn't possible; I wouldn't mind doing standalone derivation, but `DiffTime` doesn't export its constructor, so I can't write a standalone deriving instance for that.

Are there any plans to export a `Generic` instance for `DiffTime`/`UTCTime` etc., or is this strictly against the spirit of the library?

**Comment by sboosali** [comment]
any update on this? I like to derive as many instances of my types from the "standard" libraries, like generic and hashable, as I can.

**Comment by hvr** [comment]
Well, one thing to consider here is that providing `Generic` instances breaks the abstraction that hiding constructors achieves. Once you start exposing a `Generic` instance, changes to the internal implementation of said types have to be considered changes of the publicly exposed API. In some way it'd be better to just provide `.Internal` modules with the exposed constructors than define a `Generic` instance.

**Comment by AshleyYakeley** [comment]
I don't plan on exposing the constructors of `DiffTime` or `UTCTime`. You should treat them as atomic types when using generics.
