### ISSUE TITLE
Show instance for LocalTime should emit valid Haskell expression

### ISSUE THREAD

**Issue by amigalemming** [haskell/time#46]
~~~~
Prelude> import Data.Time.Format
Prelude Data.Time.Format> parseTimeM True defaultTimeLocale "%H:%M:%S" "12:34:56" :: Maybe Data.Time.LocalTime.LocalTime
Loading package array-0.4.0.0 ... linking ... done.
Loading package deepseq-1.3.0.0 ... linking ... done.
Loading package time-1.5.0.1 ... linking ... done.
Just 1970-01-01 12:34:56
~~~~
However, `Just 1970-01-01 12:34:56` is not a valid Haskell expression. Instead, `parseTimeM ... "1970-01-01 12:34:56"` would be or something that allows to construct a `LocalTime`. `Show` and `Read` are for formatting and parsing Haskell expressions. Text exchange for users must be done with `formatTime`, `parseTime` and friends, instead.
I guess that same problem occurs for the other time types.

**Comment by dmcclean** [comment]
Also `UTCTime`

**Comment by AshleyYakeley** [comment]
I'm not sure that's the expectation? `show` prints it out in the most expected format.

**Comment by amigalemming** [comment]
I'd call it the most common abuse.
But 'deriving Show' always generates Haskell expressions and this does not mix well non-Haskell representations. However, I proposed to emit something like `parseTimeM ... "1970-01-01 12:34:56"`. That's both human- and Haskell-readable.

**Comment by hvr** [comment]
Btw, even rendering as a String, e.g. `Just "1970-01-01 12:34:56"`, as if there was an `IsString` instance (which I am *not* advocating for) would be an improvement over the current state.

**Comment by AshleyYakeley** [comment]
I'm still not sure what the expectation is? The documentation for `Show` says "Convert a value to a readable `String`", but it's not clear whether "readable" means "`read`able" or merely human-readable.

**Comment by amigalemming** [comment]
On Fri, 19 Aug 2016, Ashley Yakeley wrote:

> I'm still not sure what the expectation is? The documentation for Show 
> says "Convert a value to a readable String", but it's not clear whether 
> "readable" means "readable" or merely human-readable.

I think the design of showsPrec is clearly tailored to Haskell expressions 
with their precedence values from 0 to 11 and the special support for 
Haskell's string literals via showList.

**Comment by AshleyYakeley** [comment]
Perhaps, but that isn't mentioned in the documentation. It just says "readable". And actually I think `read . show` is `id` for `LocalTime` and `UTCTime`.

**Comment by AshleyYakeley** [comment]
I'm going to close this if there isn't documentation that `show` is intended to give Haskell expressions. The cost to changing this is probably silently breaking programs.

**Comment by hvr** [comment]
@AshleyYakeley actually, the Haskell 2010 report does state something to that end in [Ch 11](https://www.haskell.org/onlinereport/haskell2010/haskellch11.html#x18-18600011.4):

> **The result of `show` is a syntactically correct Haskell expression** containing only constants, given the fixity declarations in force at the point where the type is declared. It contains only the constructor names defined in the data type, parentheses, and spaces. When labelled constructor fields are used, braces, commas, field names, and equal signs are also used. Parentheses are only added where needed, ignoring associativity. No line breaks are added. The result of show is readable by read if all component types are readable. (This is true for all instances defined in the Prelude but may not be true for user-defined instances.)

**Comment by AshleyYakeley** [comment]
That's referring to _derived_ instances of `Show`, i.e., what Haskell does by default if you don't provide your own instance, as a kind of best attempt. It's descriptive, not normative.

**Comment by ddssff** [comment]
Of course, if the Show instance for UTCTime doesn't emit a haskell expression it means the generated Show instance for any type containing a UTCTime no longer conforms to the specification in Chapter 11 mentioned above.  Though I appreciate the cost of changing this.

**Comment by AshleyYakeley** [comment]
Section 11.4 "Derived instances of Read and Show" does not specify the behaviour of all `Show` instances, only derived instances. It is specifying compiler behaviour, not user program behaviour.

> (This is true for all instances defined in the Prelude but **may not be true for user-defined instances**.)

There is no conformance issue here.

**Comment by amigalemming** [comment]
That's what @ddssff said: If you define `data T = Cons UTCTime MoreData deriving Show` then `show` for `T` will not emit a valid Haskell expression.

**Comment by AshleyYakeley** [comment]
In that case `T` would be a user-defined instance, and the condition "may not be true for user-defined instances".

**Comment by ddssff** [comment]
I guess there is some question whether or not a Show instance generated by the compiler is "user defined".

**Comment by AshleyYakeley** [comment]
No, there is no question. The sentence is clearly comparing "user defined instances" with "instances defined in the Prelude".

**There is no rule that `show` must return a Haskell expression.** I would appreciate it if others on this thread would stop trying to invent one.
