### ISSUE TITLE
time-1.6 breaks ghc-7.10.3?

### ISSUE THREAD

**Issue by ciez** [haskell/time#47]
just tried to install time-1.6 with ghc-7.10.3

got:

cabal: The following packages are likely to be broken by the reinstalls:
process-1.2.3.0
ghc-7.10.3
Cabal-1.22.5.0
haskeline-0.7.2.1
directory-1.2.2.0
hpc-0.6.0.2
bin-package-db-0.0.0.0

any suggestions?

**Comment by hvr** [comment]
First off, why are you trying to install `time-1.6` in the first place?

Other than that, with cabal < 1.24 your best option is to use per project `cabal sandbox`es. With cabal 1.24 and later there may be [other options](http://blog.ezyang.com/2015/09/is-no-reinstall-cabal-coming-to-ghc-8/)

**Comment by ciez** [comment]
> why are you trying to install time-1.6 in the first place?
need  **diffTimeToPicoseconds** which is new in 1.6

yes I use sandbox however time is bundled with base which is outside sandbox.
anyway, I made a clone project, renamed it and installed alongside 1.5.0.1

ta
