### ISSUE TITLE
formatTime does not allow width specifiers

### ISSUE THREAD

**Issue by tebello-thejane** [haskell/time#48]
It would appear that this would not be a trivial feature to add, but essentially it would be great if one could specify a width for some of the values (currently I'm thinking about displaying milliseconds truncated to 3 decimal places -- `%q` is just too damn long).

Although the format specifier syntax matches `glibc` quite well, there is this extra bit that's missing (http://linux.die.net/man/3/strftime): 

> An optional decimal width specifier may follow the (possibly absent) flag. If the natural size of the field is smaller than this width, then the result string is padded (on the left) to the specified width.

**Comment by AshleyYakeley** [comment]
I'm making some progress on this on the format-widths branch.

**Comment by AshleyYakeley** [comment]
OK, this is merged into master and will be in time-1.8.
