### ISSUE TITLE
ZonedTime missing Eq instance

### ISSUE THREAD

**Issue by lwdye** [haskell/time#50]
ZonedTime is missing an instance of Eq.  It seems that converting to UTC and comparing would be the correct implementation.

**Comment by hvr** [comment]
@lwdye the very reason we don't have an `Eq` instance for that is because the seemingly obvious implementation would violate `Eq`s laws

**Comment by pweaver** [comment]
Why wouldn't (zonedTimeToUTC  t, zonedTimeZone tz) function for both Ord and Eq according to laws and ~ according to expectation?

**Comment by saurabhnanda** [comment]
Just got hit by this issue. What laws of `Eq` would be violated here? The two components of `ZonedTime` seem to have `Eq` instances of their own, as a combination, why can't they have an `Eq` instance? What's the subtlety that I'm missing here? (And I'm sure there is something subtle going on, given my experience with times & timezones!)

**Comment by saurabhnanda** [comment]
For anyone else discovering this issue in the future, [here's the discussion](https://github.com/haskell/time/issues/16)
