### ISSUE TITLE
There should be a way to get the DiffTime from an AbsoluteTime

### ISSUE THREAD

**Issue by seagreen** [haskell/time#51]

**Comment by seagreen** [comment]
I'd be happy to make a PR if you think this is a good thing to do.

**Comment by hvr** [comment]
I assume you know about `diffAbsoluteTime :: AbsoluteTime -> AbsoluteTime -> DiffTime`?

**Comment by seagreen** [comment]
Thanks! It looks like `diffAbsoluteTime` with `taiEpoch` as the second argument gets me what I want. That's a slightly roundabout way to unwrap a newtype, perhaps the doc comment on `AbsoluteTime` should suggest it? Though I guess most people will be able to figure it out.

**Comment by seagreen** [comment]
I'll close this on the assumption that most people will do a better job than me figuring out how to get the correct `DiffTime`:)
