### ISSUE TITLE
Make it possible to format times to the W3C Datetime format

### ISSUE THREAD

**Issue by mightybyte** [haskell/time#52]
The W3C Datetime format (https://www.w3.org/TR/NOTE-datetime) wants the timezone to be formatted as "+01:00".  I didn't see any way to make the format functions in this package output that format.  It looks like only "+0100" is possible.  It would be nice to also support the "+01:00" format.

**Comment by AshleyYakeley** [comment]
Just need to pick a letter for the "%" format specifier...

**Comment by AshleyYakeley** [comment]
fix merged
