### ISSUE TITLE
TimeZone of a LocalTime

### ISSUE THREAD

**Issue by guyonvarch** [haskell/time#53]
Hello,

I want the `UTCTime` associated to a `LocalTime`. In order to convert a `LocalTime` to `UTCTime`, I need a `TimeZone`. But I can't figure out how to get the `TimeZone` associated to a `LocalTime`. In the following example, I use `getTimeZone` with the `UTCTime` constructed from the `Day` and `TimeOfDay`, but it does not relate to the same time as the `LocalTime`, that is why I don't get the final `UTCTime` I am searching for.

``` haskell
import Data.Time.Clock (UTCTime(..))
import Data.Time.Calendar (fromGregorian)
import Data.Time.LocalTime (LocalTime(..), TimeOfDay(..), localTimeToUTC, getTimeZone, timeOfDayToTime)

main :: IO ()
main = do
  let day = fromGregorian 2016 10 30
  let timeOfDay = TimeOfDay 1 0 0
  let localTime = LocalTime day timeOfDay
  timeZone <- getTimeZone (UTCTime day (timeOfDayToTime timeOfDay))
  let utcTime = localTimeToUTC timeZone localTime
  putStrLn (show utcTime)
```

It shows `2016-10-30 00:00:00 UTC` but I want `2016-10-29 23:00:00 UTC`. There is no problem with the time library, I just don't know how to get the correct time zone associated with my local time.

In France, on 2016-10-30 at 3 o'clock, the hour change and we get back at 2 o'clock. The time zone change from CEST to CET, the time library get this correctly:

``` haskell
getTimeZone (UTCTime (fromGregorian 2016 10 30) (timeOfDayToTime (TimeOfDay 0 0 0))) -- 2h in France
CEST
getTimeZone (UTCTime (fromGregorian 2016 10 30) (timeOfDayToTime (TimeOfDay 1 0 0))) -- 2h in France
CET
```

I would need a function: 

``` haskell 
getTimeZone :: LocalTime -> IO TimeZone
```

My use case for this need is I want to get `UTCTime` at the beginning of the current week and the previous week, for notification purposes. I successfully get local times but can't get for sure correct utc times.

Is this function missing or am I missing something ?

**Comment by AshleyYakeley** [comment]
A `LocalTime` doesn't contain the `TimeZone`. You probably want `ZonedTime`, which does contain a `TimeZone`.

**Comment by guyonvarch** [comment]
Yes, I could use `ZonedTime` in order to get the according `UTCTime` with `zonedTimeToUTC`, but I still don't know how to get the correct `TimeZone` in order to create the `ZonedTime`, I am just able to feed the `LocalTime` part of the `ZonedTime`.

**Comment by AshleyYakeley** [comment]
OK, I understand now. I'm looking through the libc time documentation to see whether it can be done...

**Comment by guyonvarch** [comment]
Super, thank's !

**Comment by AshleyYakeley** [comment]
AFAICT there's no direct way to do this with the libc time functions. However, it can be done iteratively:

1. given a `TimeZone` (and your `LocalTime`) get the `UTCTime` (with `localTimeToUTC`)
1. given a `UTCTime`, get the `TimeZone` (with `getTimeZone`)

If you start with an arbitrary `TimeZone`, e.g `utc`, the cycle should stabilise in one or two iterations.

**Comment by AshleyYakeley** [comment]
Strictly, though, `LocalTime` can be ambiguous at summertime time changes (in the "fall back" transition when the local time 02:00 to 03:00 is repeated). For this reason, the time library shouldn't provide this.
