### ISSUE TITLE
Memory Leak in getCurrentTime

### ISSUE THREAD

**Issue by AshleyYakeley** [haskell/time#56]
Received from Zoran Bosnjak:

```
please consider this test program:

---
import Data.Time

main = do
    getCurrentTime >>= print
    main
---

If I let this program run for some time, it would slowly consume more and
more memory, for example:
- at program startup, it is using 4168k
- after a minute or so, it goes to 4436k
- after few more minutes it stabilizes at 4700k bytes
There is a small difference on each run, but the same observation.

Is it possible, that some dynamic memory allocation of the time library is
the reason for this?
I would appreciate if you can check it.

I am working on long running process which is not running with constant
memory as it is suppose to run. There are for sure some other reasons too,
but I think that this test program is not suppose to behave like this.

I am checking memory by running "cat /proc/<pid>/status | grep VmRSS"
My environment is linux 3.19, ghc 8.0.1.
```

**Comment by AshleyYakeley** [comment]
It's possible PR 55 will fix this.

**Comment by AshleyYakeley** [comment]
This could also be caused by buffering of stdout?

**Comment by winterland1989** [comment]
Though there're lots of thunk creating during current time's implementation, i'm not convinced this is a bug, especially after few more minutes it will be stabilized. Stdout buffering may be the reason, and providing GC statistic for all different running time will be helpful.

**Comment by AshleyYakeley** [comment]
When I tried it, it started off at 4412k, and then jumped to 4676k, where it stayed for over 20 minutes. This doesn't look like a memory leak to me.

**Comment by zoranbosnjak** [comment]
Indeed, this might not be a bug after all. Without using stdout, there is no problem. Thanks for the analysis.
