### ISSUE TITLE
1.8 branch

### ISSUE THREAD

**Issue by ezyang** [haskell/time#59]
Hey all, according to https://github.com/haskell/time/pull/58 the version of time that will be released with GHC 8.2 will be 1.8. As such, I would quite appreciate the cutting a 1.8 branch, so we can start backporting fixes (in particular, I need the patch from that PR to fix the GHC build with the new version of Cabal.) Thanks!

**Comment by AshleyYakeley** [comment]
This may need to be a 1.7.0.1.

**Comment by AshleyYakeley** [comment]
OK, I have released 1.7.0.1 with your patch. Please use that for the time being.

**Comment by hvr** [comment]
@AshleyYakeley I believe for 1.7.0.1 to be useful to @ezyang, it  1.7.0.1 needs to exist as a git commit somewhere in this git repo (preferably inside a branched off "1.7" maintainance branch) so that we can refer to it as a Git submodule gitlink.

**Comment by AshleyYakeley** [comment]
Tag 1.7.0.1 should exist?

**Comment by hvr** [comment]
@AshleyYakeley ok, now I'm totally confused... I assumed `master` still had those POSIXTime/RawTime changes... nevermind then

**Comment by ezyang** [comment]
It's very confusing viewing `git log` because the "Set version to 1.7.0.1" commit (b6098be8a4facfa854c633f2a3a82ab8e72962ef) has a later time than the "Set version to 1.8" commit (b66209034d660f6c8a14522f09745b277d5280b9), so Git reports it later. I didn't figure it out until I looked at the actual graph in gitk. Anyway, this is good enough for me!

**Comment by AshleyYakeley** [comment]
The commit messages simply refer to the changes I made to the .cabal file, not to actual releases.
