### ISSUE TITLE
Int vs Integer for representing year

### ISSUE THREAD

**Issue by saurabhnanda** [haskell/time#60]
How come `mondayStartWeek` returns year as `Int` and `fromMondayStartWeek` accepts year as an `Integer`?

https://www.stackage.org/haddock/lts-7.14/time-1.6.0.1/Data-Time-Calendar-OrdinalDate.html#v:mondayStartWeek vs https://www.stackage.org/haddock/lts-7.14/time-1.6.0.1/Data-Time-Calendar-OrdinalDate.html#v:fromMondayStartWeek

**Comment by AshleyYakeley** [comment]
`mondayStartWeek` doesn't return a year. It returns a pair, the first part is week-in-the-year, in the range 0 to 53. The second part is the day of the week, in range 1 to 7.

That said, it was probably the wrong decision to use `Integer` instead of `Int` to represent years.
