### ISSUE TITLE
Valid UTCTime construction

### ISSUE THREAD

**Issue by defanor** [haskell/time#61]
Since the `DiffTime` part of `UTCTime` should be in [0,86400s] (according to its description), it requires a check to ensure that it actually is, what would be nice to abstract into a function: as @phadej suggested on https://github.com/bos/aeson/issues/500#issuecomment-270623957, there is a few options (including clipping, rolling over, failing).

Besides, a function (maybe a separate one though, but it may be particularly suitable for this one) that would construct time out of regular time components (hours, minutes, etc) may be handy by itself.

Another somewhat related issue, which may be fixed with this, is that `parseTimeM` sometimes fails to parse what `formatTime` printed (e.g., on 100 seconds), and sometimes prints/parses it in a way that violates the invariant (e.g., on 99 seconds). Those 61-99 seconds seem to fall under "unspecified behaviour", but perhaps it would be better to specify it in a way that at least vaguely makes sense (say, roll over, using the proposed function).

**Comment by AshleyYakeley** [comment]
There are several issues here. The third paragraph suggests you've found a bug? Could you find an example of code that gives incorrect result and enter a new issue for it?

**Comment by defanor** [comment]
I'm not sure if that's a bug, since a very similar behaviour in the
linked aeson issue wasn't considered to be one (because there should not
be 61+ seconds in the first place): more like a few related things to
sort out, perhaps.

Here is the code to demonstrate it:

λ> let t s = UTCTime (fromGregorian 2017 2 8) (secondsToDiffTime $ 24 * 3600 + s)
λ> let formatISO = formatTime defaultTimeLocale (iso8601DateFormat $ Just "%H:%M:%S")
λ> let parseISO = parseTimeM False defaultTimeLocale "%Y-%m-%dT%H:%M:%S"
λ> let test = parseISO . formatISO . t :: Integer -> Maybe UTCTime
λ> test 0
Just 2017-02-08 23:59:60 UTC
λ> test 39
Just 2017-02-08 23:59:99 UTC
λ> test 40
Nothing
λ> formatISO (t 40)
"2017-02-08T23:59:100"

**Comment by AshleyYakeley** [comment]
It's awkward, because we cannot always determine whether a time is correct, since we don't know when leap seconds are. Rolling over 86401 would definitely be the wrong thing to do, for example.

**Comment by defanor** [comment]
Other functions just ignore the existence of leap seconds, including
roll over cases:

λ> let t1 = UTCTime (fromGregorian 2016 12 31) (secondsToDiffTime $ 24 * 3600 - 1)
λ> let t2 = UTCTime (fromGregorian 2017 01 01) (secondsToDiffTime 0)
λ> diffUTCTime t2 t1
1s
λ> addUTCTime 1 t1
2017-01-01 00:00:00 UTC
λ> let t3 = UTCTime (fromGregorian 2016 12 31) (secondsToDiffTime $ 24 * 3600)
λ> diffUTCTime t3 t2
0s

So maybe this one also should. And maybe the maximum value should be
86399 then.

I guess it would be plenty of work to extend the library to support leap
seconds more or less properly (it would probably require new types, and
user-provided lists of known dates when leap seconds have occured), but
it's not specific to this issue.

**Comment by AshleyYakeley** [comment]
It's specified in the types. `addUTCTime` and `diffUTCTime` use `NominalDiffTime`, which ignores leap seconds. However, the `utctDayTime` member of `UTCTime` is `DiffTime` which accounts for leap seconds.

In short, it's reasonable to do rollover, etc., when working with `NominalDiffTime`, but not with `DiffTime`.

**Comment by AshleyYakeley** [comment]
Note the library already has types and functions for working with user-provided lists of known dates when leap seconds have occured: see `Data.Time.Clock.TAI`.

**Comment by defanor** [comment]
Didn't know about TAI, thanks for pointing it out.

If using NominalDiffTime allows to do roll overs (this gets somewhat
confusing though), maybe the construction-with-validation function could
be just like addUTCTime, but also constructing UTCTime for midnight of a
given date? I.e.:

validatedTime y m d s = addUTCTime s (UTCTime (fromGregorian y m d) 0)

That doesn't feel quite right though -- like a hack around a convention.

**Comment by AshleyYakeley** [comment]
I don't see an obvious improvement to be made here.
