### ISSUE TITLE
Undefined symbol (CTimespec)

### ISSUE THREAD

**Issue by luntain** [haskell/time#64]
I'm getting this linking error when building ghc-mod using stackage lts-8.4:

```
Linking .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/ghc-mod/ghc-mod ...
    Undefined symbols for architecture x86_64:
      "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_closure", referenced from:
          _SigH_srt in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
      "_timezm1zi6zi0zi1_DataziTimeziClockziCTimespec_getCTimespec1_info", referenced from:
          _cikh_info in libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog.a(Random.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    `gcc' failed in phase `Linker'. (Exit code: 1)
```
Is it because of the #if macro in:
`lib/Data/Time/Clock/Internal/CTimespec.hsc:#if !defined(mingw32_HOST_OS) && HAVE_CLOCK_GETTIME`
?

Somehow time is built without a symbol that random is expecting. I am doing it on osx 10.12.3 (sierra). Is that symbol supposed to be missing on my system?

**Comment by luntain** [comment]
It must have something to do with Sierra adding clock_gettime: https://ghc.haskell.org/trac/ghc/ticket/12858

**Comment by luntain** [comment]
@bgamari Can you comment since you closed that ticket with clock_gettime in Sierra. Can it be that since I downloaded ghc which came with already built time packge, it lacks the module guarded by the HAVE_CLOCK_GETTIME, but when I build random on Sierra, that guard no longer suppresses the module and random expects the module to be there? Would I get rid of that error by building ghc on my machine?

**Comment by luntain** [comment]
Found a workaround. Simply passing the `--with-gcc` flag prevents the linker error. I don't know why.
`stack --with-gcc=$(which gcc) build ghc-mod`

**Comment by AshleyYakeley** [comment]
Does it help to delete your `.stack-work`? I sometimes get linker errors that can be resolved that way.

**Comment by luntain** [comment]
I was building it on top level. Deleting `~/.stack` and starting from scratch did not reproduce the linking error.
