### ISSUE TITLE
Include a DayOfWeek enumeration

### ISSUE THREAD

**Issue by mightybyte** [haskell/time#69]
Since this is pretty much the de-facto Haskell library for manipulating dates and times, it seems that it should provide a DayOfWeek enumeration like this:

    data DayOfWeek
        = Sunday
        | Monday
        | Tuesday
        | Wednesday
        | Thursday
        | Friday
        | Saturday

What are your thoughts on adding something like this?

**Comment by hvr** [comment]
Just wondering, which instances would `DayOfWeek` provide?

**Comment by mightybyte** [comment]
I don't have a strong opinion, but my first instinct would be:

    deriving (Eq,Ord,Show,Read,Enum,Bounded)

But I guess we might also need to include Data, Typeable, Generic, and maybe NFData?

I don't care which day is the start of the week.  Going with ISO-8601 seems to be decent argument.

**Comment by AshleyYakeley** [comment]
Could you give some examples where it might be useful?

**Comment by mightybyte** [comment]
I just wanted the type and thought that should be available in some standardized place.  This package is the first place that came to mind.  I wanted the enum for the standard reason you want enums instead of ints...so you can avoid having to worry about invalid inputs.

**Comment by kanishka-azimi** [comment]
Consider using numbers internally and making the name a formatted version of the value, requiring a locale as an argument to the format function

**Comment by mightybyte** [comment]
I don't want numbers internally because that's exactly the type of thing that Haskell's type system allows us to avoid.  I want a strongly typed enumeration with 7 semantic values.  That way I never have to worry about invalid values.

**Comment by AshleyYakeley** [comment]
Is it allowable to make circular instances of `Enum`? In which case I would say not `Ord` or `Bounded`.

**Comment by mightybyte** [comment]
I wouldn't say that circularity is important here.  The point of this type is to be an enumeration of the precisely seven days in a week.

While `Ord` isn't a superclass of `Enum`, there is an implicit ordering wound up in `Enum`, so I don't think it's unreasonable to include both `Ord` and `Bounded`.  Part of the point of this type is to be able to get a list of all the days of the week.  `[minBound..maxBound]` is the most convenient way to do that.  I think it should be pretty obvious to users of this type that there is an implicit ordering and that that ordering might not match their assumed ordering.  Picking a common ordering still has value for the people that are ok with that ordering.

But if it comes down to having this type without `Ord` and `Bounded` versus not having the type at all, I'd definitely go with leaving out those instances.

**Comment by nickolasacosta** [comment]
Would this be a decent use case? 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since
The `If-Modified-Since` HTTP header expects dates into a format like so:
```
If-Modified-Since: Wed, 21 Oct 2015 07:28:00 GMT
```

**Comment by peti** [comment]
> Is it allowable to make circular instances of Enum?

No. `succ maxBound` should be undefined, The set of DayOfWeek constructors is finite and the type should be bounded so that `[minBound..maxBound]` enumerates all possible constructors. And, of course, the ISO-8601 standard should be followed, so `fmap fromEnum [Monday..Sunday] = [1..7]`.

**Comment by AshleyYakeley** [comment]
That's only the case if there is an instance of `Bounded`. If there is an instance of `Enum` but not `Bounded`, I don't see why it couldn't be circular. Every day of the week has a successor.

**Comment by AshleyYakeley** [comment]
`[Friday..Tuesday]` should give the expected result.

**Comment by AshleyYakeley** [comment]
`zip [1..30] [Wednesday..]` should give the expected result.

**Comment by peti** [comment]
Well, I see your point. The nice thing about a circular `Enum` instance is that `succ` and `pred` are total functions. And the ability to say either `[Monday..Sunday]` or `[Sunday..Saturday]` is pretty neat, too. It's an unusual `Enum` instance, for sure, but I'd be happy with that API.

What's important to me is mostly that `fromEnum Monday = 1` as per ISO-8601, so that I can use this type to represent the `Int` values used by  `toWeekDate` et al in a more type-safe manner.

**Comment by AshleyYakeley** [comment]
`fromEnum` returning 1..7 (instead of 0..6) is non-standard but still OK I think?

Certainly `toEnum` should work in the obvious mod 7 way.

**Comment by peti** [comment]
> fromEnum returning 1..7 (instead of 0..6) is non-standard but still OK I think?

I think that is an important feature of that definition.

> Certainly toEnum should work in the obvious mod 7 way.

The correct `mod 7` expression for that definition strikes me as rather non-obvious, to be honest, but I know what you mean. :-)

**Comment by AshleyYakeley** [comment]
Merged.

**Comment by mightybyte** [comment]
Thanks, this looks great!
