### ISSUE TITLE
What incompatible/breaking changes should one look out for when upgrading to/allowing time-1.8?

### ISSUE THREAD

**Issue by hvr** [haskell/time#72]
I'm trying to understand which breaking changes I need to look out for in time-1.8, i.e. when is it safe to upgrade to (i.e. relax upper bounds to allow)  time-1.8 (IOW, when does "it compiles" equate to "it's compatible") ?

The changelog entry for 1.8 seems harmless to me, i.e. it looks merely like API additions, no real breaking changes?

> ## [1.8]
> - Added SystemTime
> - Data.Time.Format: allow padding widths in specifiers for formatting (but not parsing)
> - Test: use tasty, general clean-up
> - Test: separate out UNIX-specific tests, so the others can be run on Windows
> - Clean up haddock.

/cc @phadej @bergmark

**Comment by AshleyYakeley** [comment]
Probably??

**Comment by AshleyYakeley** [comment]
I think if it compiles, it's the same and 1.7.

**Comment by hvr** [comment]
@AshleyYakeley alright, thanks!
