### ISSUE TITLE
parseTimeM succeeds on nonsensical zones with %Z

### ISSUE THREAD

**Issue by jberryman** [haskell/time#75]
> parseTimeM True defaultTimeLocale "%Y-%m-%d %H:%M:%S %Z" "2017-01-28 10:11:11 EDT" :: Maybe UTCTime
    Just 2017-01-28 14:11:11 UTC
    > parseTimeM True defaultTimeLocale "%Y-%m-%d %H:%M:%S %Z" "2017-01-28 10:11:11 eastern" :: Maybe UTCTime
    Just 2017-01-28 10:11:11 UTC

This is documented behavior but doesn't make sense to me: after all you have a list of zone names in the `TimeLocale` I just passed in. In any case this makes the function with `%Z` pretty useless.

The same sort of complaint as #70

**Comment by jberryman** [comment]
The issue's certainly here (it falls back to UTC), but I don't understand what this is meant to do, nor the docs for `buildTime`:

```
instance ParseTime TimeZone where
    buildTime l = let
        f (TimeZone _ dst name) ('z',x) | Just offset <- readTzOffset x = TimeZone offset dst name
        f t ('Z',"") = t
        f _ ('Z',x) | Just zone <- getKnownTimeZone l x = zone
        f _ ('Z',[c]) | Just zone <- getMilZone c = zone
        f (TimeZone offset dst _) ('Z',x) | isAlpha (head x) = TimeZone offset dst (up x)
        f (TimeZone _ dst name) ('Z',x) | Just offset <- readTzOffset x = TimeZone offset dst name
        f t _ = t
        in Just . foldl f (minutesToTimeZone 0)
```

**Comment by 8084** [comment]
I think that the fact that `%Z` also accepts offsets should also be mentioned in format specification for [formatTime](https://hackage.haskell.org/package/time-1.8.0.3/docs/Data-Time-Format.html#v:formatTime) which currently states the following:

```
%z
    timezone offset in the format -HHMM.
%Z
    timezone name
```

**Comment by AshleyYakeley** [comment]
@8084 this is already mentioned in the documentation for `parseTimeM`.

**Comment by AshleyYakeley** [comment]
fix merged
