### ISSUE TITLE
`show (TimeOfDay minBound 0 0)` is an infinite string of minus signs

### ISSUE THREAD

**Issue by jberryman** [haskell/time#77]
I haven't looked into this, but I'm sure this is due to something like: 

```
badShow n | 0 > n = "-" ++ badShow (negate n)
          | otherwise = -- this is never reached when n = minBound
```

which is incorrect for `minBound` in two's complement. Fun fact: I just reported this same bug in a completely unrelated package today.

This brings up the broader question of what really `time` is supposed to be doing in the case of values which (arguably) shouldn't be representable. In some cases time operations work as you'd expect, even though the intermediate values "overflow", etc.

**Comment by AshleyYakeley** [comment]
Fix merged.

**Comment by jberryman** [comment]
Thanks!

**Comment by AshleyYakeley** [comment]
This is in the 1.8.0.4 release on Hackage. It probably won't be in Stackage until a new GHC release, though.
