### ISSUE TITLE
Run tests in travis builds

### ISSUE THREAD

**Issue by AshleyYakeley** [haskell/time#85]

**Comment by AshleyYakeley** [comment]
Not easy to do with the cabal-install system. This would probably involve switching to a stack-based system instead, which may have its own problems.

**Comment by cartazio** [comment]
its pretty easy to setup, i or another hackage trustee / or CLC member who's comfy with that stuff could help you

**Comment by cartazio** [comment]
you may want help to migrate again .  travis is now defunct, cc @Bodigrim @phadej @emilypi   for help
