### ISSUE TITLE
Docs about numeric instances for NominalDiffTime

### ISSUE THREAD

**Issue by chris-martin** [haskell/time#86]
It's pretty common to want to convert a `UTCTime` to an `Int` or `Integer` number of seconds or milliseconds since the unix epoch. Although the `time` library actually does make this pretty easy, to do so you need to notice the `RealFrac` instance, which is not entirely obvious (especially if you're a beginner not yet fully acclimated to the rather tedious numeric classes in `base`).

A couple examples of confusion:

* https://stackoverflow.com/questions/42843882
* https://twitter.com/nuttycom/status/961694394154852353

The haddocks for `NominalDiffTime`, `POSIXTime`, and `utcTimeToPOSIXSeconds` would be great places to point out the numeric instances and include some usage examples.

**Comment by harendra-kumar** [comment]
A huge plus to this issue. This not easily discoverable when trying to use the time library for the first time.

When I started to use Haskell I was thoroughly puzzled how to even make `NominalDiffTime` from number of seconds. Later I figured out that `fromInteger` can be used. We need to call that out explicitly under the docs of `NominalDiffTime`. 

It was specially more puzzling because `DiffTime` has a `secondsToDiffTime` function. So one would suspect that it must be missing from `NominalDiffTime`. This also means that we stop looking for other possibilities.

**Comment by chris-martin** [comment]
It is unfortunate, I think, that the names of `DiffTime` and `NominalDiffTime` do not include the word "seconds," as it is a critical aspect of what they are. We will need to emphasize this more.

**Comment by AshleyYakeley** [comment]
So time differences are essentially a one-dimensional vector space (and time is an additive torsor on time differences). The natural operations are zero/addition/negation/subtraction (as a group), scaling by reals, and dividing one time by another to get a real number. Sadly classes representing such operations are not available in base or the core libraries that can time can depend on, so the `NominalDiffTime` type is crammed into the `Num` class.

However, it might be useful for users to write their code as if `NominalDiffTime` were represented more cleanly as a one-dimensional vector space, with no special status given to the second as a time unit. To that end, the simplest thing would be to just add explicit functions:
```
secondsToNominalDiffTime :: Pico -> NominalDiffTime
nominalDiffTimeToSeconds :: NominalDiffTime -> Pico
```
I think this would make user code more legible, as it would be clear where the conversion was happening.

**Comment by chris-martin** [comment]
Yes, I think function additions would be the best solution. Both the API discoverability of the time library, and the clarity of code that uses the time library, would benefit from `NominalDiffTime`/seconds conversions functions that have the word "seconds" in the name.

**Comment by harendra-kumar** [comment]
Yes, I agree, that will also make it consistent with the `DiffTime` API.

**Comment by AshleyYakeley** [comment]
Merged into master.
