### ISSUE TITLE
UTCTime constructed with values of DiffTime beyond 86400

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/time#87]
UTCTime is defined like this:

```haskell
data UTCTime = UTCTime {
    -- | the day
    utctDay :: Day,
    -- | the time from midnight, 0 <= t < 86401s (because of leap-seconds)
    utctDayTime :: DiffTime
}
```

Now, `DiffTime` can be have any value beyond 86400. It is possible to construct values of UTCTime with those values. What does it mean? Usually it does not make sense. If the construction is left open to arbitrary values, is it designed to account for leap seconds? Or is it just a bad design or mistake?

If it is by design, can we have a better less puzzling design to explicitly accommodate leap seconds. Or at least this be explained well in the documentation.

Notice the number of seconds printed in this, is this by design?:

```
Prelude Data.Time> UTCTime (ModifiedJulianDay 1) (secondsToDiffTime 866000)
1858-11-18 23:59:779660 UTC
```

Also when adding time, any extra seconds just disappear:

```
Prelude Data.Time> addUTCTime nominalDay (UTCTime (ModifiedJulianDay 0) (secondsToDiffTime 86400))
1858-11-19 00:00:00 UTC
Prelude Data.Time> addUTCTime nominalDay (UTCTime (ModifiedJulianDay 0) (secondsToDiffTime 86401))
1858-11-19 00:00:00 UTC
Prelude Data.Time> addUTCTime nominalDay (UTCTime (ModifiedJulianDay 0) (secondsToDiffTime 86402))
1858-11-19 00:00:00 UTC
```

**Comment by AshleyYakeley** [comment]
I don't see what the problem is here? If you construct a `UTCTime` with an invalid `utctDayTime`, you will get an invalid `UTCTime`.

**Comment by harendra-kumar** [comment]
Why is it possible to construct invalid UTCTime in the first place?

**Comment by AshleyYakeley** [comment]
The `UTCTime` constructor is exposed, so you can create whatever you want. You'll get similar behaviour if you create an invalid `TimeOfDay`: 
```
> TimeOfDay 65 (-13) (-4)
65:-13:0-4
```
I'm not sure what you want here?

**Comment by harendra-kumar** [comment]
> The UTCTime constructor is exposed, so you can create whatever you want.

That is precisely the problem. Why is it designed like that? I should not be able to construct invalid values accidentally and be able to write a program that misbehaves. Why expose the constructor if it allows illegal values to be constructed? why can't we use smart constructors to construct the values then?

Currently I can construct a any `DiffTime` and use that to construct a `UTCTime` without knowing that it is incorrect if the `DiffTime` is more than 86400. That should not happen.

**Comment by AshleyYakeley** [comment]
This could be done for `TimeOfDay`, but it would be a bad idea to do this for `UTCTime`.

`utctDayTime` should be in the range [0,86401), and it would be possible to create a construction function that validates this. But users of the time library would then rely on this validation, and not do their own validation, and that would be very dangerous, as it would allow leap-second values when the user did not expect them.

By not creating a validating constructor function, it becomes the responsibility of the user to make sure that the `utctDayTime` value is in a range they expect. For most users, that range is [0,86400), while for a few others, it is [0,86401), and the library cannot know which.

**Comment by harendra-kumar** [comment]
Ah, that is precisely what I was suspecting initially, in my question I asked this:
> If the construction is left open to arbitrary values, is it designed to account for leap seconds? Or is it just a bad design or mistake?

Now you answered it to the point. Thank you. Then my next question was:

>If it is by design, can we have a better less puzzling design to explicitly accommodate leap seconds. Or at least this be explained well in the documentation.

Also, can we fix `TimeOfDay`? It also seems to be accommodating leap seconds:

```
Note that 0 <= todSec < 61, accomodating leap seconds. Any local minute may have a leap second, since leap seconds happen in all zones simultaneously
```

**Comment by AshleyYakeley** [comment]
Ah, I was wrong, we can't create a validating constructor for `TimeOfDay` either, for the same reason...

I'm not sure what better option there is to accomodate leap-seconds in `UTCTime`?

**Comment by harendra-kumar** [comment]
Now that I understand the problem better, let me try fixing it.

**Comment by harendra-kumar** [comment]
Now, I am wondering what is the point of allowing leap seconds when we do not handle them properly:

```haskell
import Data.Time
import Control.Exception

main :: IO ()
main = do
    let t0 = UTCTime (ModifiedJulianDay 0) (secondsToDiffTime 0)
    -- day 0 is a day with 1 leap second, therefore t1 denotes the last second of day 0.
    let t1 = UTCTime (ModifiedJulianDay 0) (secondsToDiffTime 86400)
    -- t2 is day 1 and 0 seconds i.e. just 1 second after t1
    let t2 = UTCTime (ModifiedJulianDay 1) (secondsToDiffTime 0)
    -- t2' must be same as t2
    let t2' = addUTCTime (fromInteger 1) t1

    print t2
    print t2'
    assert (t2' == t2) (return ())

    let d1 = diffUTCTime t1 t0
    let d2 = diffUTCTime t2 t0

    print d1
    print d2

    assert (d2 == d1 + 1) (return ())
```

If we handle leap seconds properly the asserts in this program should not fail.

`addUTCTime`  does not care about any leap seconds, `posixSecondsToUTCTime` always assumes a day length of 86400 disregarding any leaps.

If we have to do this properly we will have to keep leap seconds separately in `UTCTime` and account for them properly in the diff/add operations. At any point all the leap seconds since the epoch should be carried in the leap seconds field. So when we diff the time we will always get the correct duration including the leap seconds, but when computing days we should not account them. `NominalDiffTime` should also distinguish leap seconds for the add/diff operations to work properly. With this, the currently broken semantics with leap seconds can be fixed.

Since the current types are not serving the expected purpose we can hide the constructors of `UTCTime` and use smart constructors so as to disallow illegal values. If we want to provide proper leap seconds handling as I described above, we can use a separate type maybe something like `UTCLeapTime` or just `UTC` and another type corresponding to `NominalDiffTime`.

**Comment by AshleyYakeley** [comment]
`NominalDiffTime` represents a nominal difference of time, that is, ignoring leap-seconds. Thus, `addUTCTime` will truncate any leap-second to the beginning of the following day.

`DiffTime` represents an actual difference of time.

**Comment by AshleyYakeley** [comment]
`NominalDiffTime` is documented:

> This is a length of time, as measured by UTC. Conversion functions will treat it as seconds. It has a precision of 10^-12 s. It ignores leap-seconds, so it's not necessarily a fixed amount of clock time. For instance, 23:00 UTC + 2 hours of NominalDiffTime = 01:00 UTC (+ 1 day), regardless of whether a leap-second intervened.

**Comment by harendra-kumar** [comment]
I have understood all that, but it does not change anything. The types and APIs are not useful for any programming operations that care for leap seconds. I cannot think of how anyone would use it, I need a sensible use case. IMO the types are just unsafe without serving any useful purpose.

**Comment by AshleyYakeley** [comment]
If you care about leap-seconds, you should be doing calculations in `AbsoluteTime`, and then converting from/to `UTCTime` with a `LeapSecondMap`.

**Comment by harendra-kumar** [comment]
That's a good news, then the problem is already solved. That means, we do not need any leap second accounting in UTCTime at all. Leap seconds just get eliminated/introduced when converting from TAI to UTCTime and vice versa. They just exist in the leap second map, they don't exist in UTCTime, we do not need any representation of leap seconds in UTCTime.

That means we can safely hide UTCTime constructors and make it safe.

**Comment by AshleyYakeley** [comment]
Leap seconds do _not_ get eliminated when converting from TAI to UTC.

**Comment by harendra-kumar** [comment]
Leap seconds must be accounted as part of days in UTC. When we convert an absolute time to UTC, we would have accounted the leap seconds in days. The question remains only about the last day of the period being converted. If the last day does not have a leap second then there is nothing to argue about, the remaining seconds will always be less than 86400. 

We are now only arguing about the case when the last day of the period has a leap second. If the remaining seconds in that day are up to 86399 then again I guess there is nothing to argue about.

The question boils down to this - if the remaining seconds are 86400, then do we call it a full day or do we return just 86400 seconds? In my opinion there is no point in returning 86400 seconds in that case we should advance the day to the next day counting the leap occurring at that point. This means whether we have 86400 seconds or 86401 seconds we will return the same UTC time and that reflects the true nature of a leap, it is a leap after all, we have to eat that one second somewhere, it has no particular designated place as to where it should be accounted. 

We do not achieve anything useful by returning `n` days and 86400 seconds in that case. First of all it is anyway arbitrary to call it 86400 seconds and not a day. Even if we do that how does it help?

**Comment by AshleyYakeley** [comment]
Consider this:
```
timeUTC = taiToUTCTime lmap timeTAI
```
If `lmap` indicates that the day indicated by `timeTAI` has a leap-second, and if `timeTAI` represents a time during that leap-second, then `utctDayTime timeUTC` will be between 86400 and 86401.

I believe this is appropriate behaviour for `taiToUTCTime`.

**Comment by harendra-kumar** [comment]
How would anyone using UTC distinguish the difference between 86400 seconds and a day? This is essentially next day plus a fraction of a second. If not that then which part of the day will this be considered in UTC? How does it help returning 86400 and not incrementing the day?

**Comment by AshleyYakeley** [comment]
Some UTC days are 86401 seconds long. The `UTCTime` type must be able to represent this.

**Comment by harendra-kumar** [comment]
Ok. Agreed that some days are 86401 seconds and we need to represent those days in as many seconds. Now we are back to my original point [here](https://github.com/haskell/time/issues/87#issuecomment-364722880) that this is broken under add/diff operations. When we have a day with leap second at 86400 seconds and we add 1 more second to it then it should go to next day at 0 seconds, currently it goes to 1 second in the next day.

**Comment by AshleyYakeley** [comment]
There's no way to know which days have leap-seconds. So all calculations involving `NominalDiffTime` ignore them.

We cannot add one _actual_ second of time to a UTCTime without a leap-second map. Instead, we add one _nominal_ second of time. Adding one nominal second is usually the same as adding one actual second, but in certain cases is the same as adding two actual seconds.

**Comment by harendra-kumar** [comment]
So we have one problem or the other in any case. If we represent a day with one extra second then we have this anomaly. Why is this a better problem to have? Why don't we choose to not represent a longer day and in return not have this anomaly? If we do that then we also get a bonus of safer types by being able to use smart constructors.

**Comment by AshleyYakeley** [comment]
`UTCTime` must be able to represent all valid UTC times. This includes leap seconds.

**Comment by harendra-kumar** [comment]
Except that it doesn't work as correctly.

**Comment by AshleyYakeley** [comment]
I believe the behaviour is correct, provided one keeps in mind the difference between nominal time differences and actual time differences.

Most people don't care about leap-seconds and will want to work entirely with nominal time differences. Thus, the functions that work with `NominalDiffTime` will truncate leap seconds to the beginning of the following day.

**Comment by harendra-kumar** [comment]
Thanks for answering my questions patiently. Though I tend to disagree with the choice of interface, I prefer a safer and easier to understand/use interface.
