### ISSUE TITLE
UTCTime: seconds above 59

### ISSUE THREAD

**Issue by KtorZ** [haskell/time#90]
Hey, I am not sure whether you are aware of this behavior, but I find it rather weird:

```hs
$> let t = UTCTime (toEnum 58000) (toEnum 86401*1e12)
$> show t
"2017-09-04 23:59:61 UTC"
$> Aeson.encode t
"\"2017-09-04T24:00:01Z\""
```
There's an implicit *contract* in the documentation about the value given to `utctDayTime` but I'd rather expect the program to loudly fail if violated instead of carrying around the wrong number of seconds. 

![image](https://user-images.githubusercontent.com/5680256/36781602-9c5cfaee-1c76-11e8-9e22-fdc474bf2c5b.png)

What's your opinion about that?

**Comment by AshleyYakeley** [comment]
This is the same as #87.
