### ISSUE TITLE
Consider migration from 'Integer' to type safe time units

### ISSUE THREAD

**Issue by ChShersh** [haskell/time#92]
Hello, maintainers of `time` package! We have developed a library called `o-clock` @serokell for type-safe time units:

* https://github.com/serokell/o-clock

There exist many such libraries, but `o-clock` differs from others in the following:

1. Well-maintained, won't be dropped and abandoned (like `time-units` package where last commit was 7 years ago).
2. Type-safe, convenient, boilerplateless.
3. Has tutorial and good documentation.
4. Doesn't contain Unicode in `Show` instance (so won't break Windows).
5. Precise: you don't lose precision while converting between time units.

So I wonder, would you consider to use `o-clock` in your package to add extra type-safety? I'll give an example. 

Instead of:

```haskell
secondsToDiffTime :: Integer -> DiffTime
diffTimeToPicoseconds :: DiffTime -> Integer
```

`time` package will have

```haskell
secondsToDiffTime :: Time Second -> DiffTime
diffTimeToPicoseconds :: DiffTime -> Time Picosecond
```

How do you feel about that? Is there anything that would stop you from migration that we can fix? 

Anyway, I just want to hear your thoughts on this design. 

Thanks in advance!

**Comment by AshleyYakeley** [comment]
`time` is a core library and cannot depend on non-core libraries.

**Comment by ChShersh** [comment]
@AshleyYakeley Okay, that makes sense. Sorry for wasting your time. Feel free to close this issue then!

**Comment by juhp** [comment]
Just noting for reference there is your `Data.Fixed` in base: eg
```haskell
> import Control.Concurrent
> import Data.Fixed
>
> threadDelay (fromEnum (5 :: Micro))
```
will wait 5s - though `toMicro`, `fromMicro`, etc would be nice to have.

(o-clock does look nice though for durations.)
