### ISSUE TITLE
UTCTime Show instance result is not a Haskell expression

### ISSUE THREAD

**Issue by ddssff** [haskell/time#93]
As a consequence, the Show instance result of any record containing a UTCTime is also not a Haskell  expression.  I'm not sure whether this is a bug, but it bugs me.

    λ> utc <- getCurrentTime
    λ> data Foo = Foo {_time :: UTCTime} deriving (Read, Show)
    λ> show (Foo utc)
    "Foo {_time = 2018-04-04 18:41:29.731449294 UTC}"

**Comment by AshleyYakeley** [comment]
It's not supposed to be a Haskell expression. See #46.

**Comment by AshleyYakeley** [comment]
Not that I know of? Haskell is a compiled language, there's no particular reason for programs that happen to be written in Haskell to emit Haskell language expressions.

**Comment by ddssff** [comment]
I mostly use this capability for building unit tests.

**Comment by amigalemming** [comment]
Another valid use of `Show` is in GHCi.
