### ISSUE TITLE
Faster parsers

### ISSUE THREAD

**Issue by parsonsmatt** [haskell/time#97]
[`parseTime` is slow](https://github.com/andrewthad/chronos/pull/18#issuecomment-399156964). It's about 5x slower than an API-compatible implementation based on `attoparsec` (from the `thyme` library) and 22x slower than a specialized attoparsec parser.

I note that the dependencies for `time` are quite minimal. Would it be acceptable to include an `attoparsec` dependency to provide a faster parser based on the one in `thyme`?

**Comment by parsonsmatt** [comment]
Adding `attoparsec` as a dependency only incurs the following extra packages (according to `stack ls dependencies`):

```
> attoparsec 0.13.2.2
16a18
> hashable 1.2.6.1
17a20
> integer-logarithms 1.0.2
27a31
> scientific 0.3.5.2
```

**Comment by AshleyYakeley** [comment]
`time` is a core library, and cannot depend on non-core libraries such as `attoparsec`.

**Comment by parsonsmatt** [comment]
Fair, thanks for clarifying :smile:
