### ISSUE TITLE
failed buid process for unix-2.7.2.2 library

### ISSUE THREAD

**Issue by Haskell-mouse** [haskell/time#98]
Hi ! 
Tried to build time library successed, but caused the following error: 

`/tmp/stack20119/unix-2.7.2.2/System/Posix/Files/ByteString.hsc:111:1: error:
   Data.Time.Clock.POSIX: Can't be safely imported!
The module itself isn't safe.
|
| import Data.Time.Clock.POSIX (POSIXTime)`

debian 9, 
stack: Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565

**Comment by Haskell-mouse** [comment]
I did not change stack.yaml, so - "lts-10.7"

**Comment by Haskell-mouse** [comment]
It is very strange, but i just deleted the whole folder and clone it again. Now it builds successfully. Sorry for an accidental issue (

**Comment by AshleyYakeley** [comment]
Were you building from git? That's not guaranteed to be stable. Generally you should use the package that is shipped with GHC, or more recent packages from Hackage or Stackage.
