### ISSUE TITLE
Please provide 'Generic' instances for UTCTime, DiffTime, etc.

### ISSUE THREAD

**Issue by peti** [haskell/time#99]
If those data types are instances of the `Generic` class, it's much easier to derive further instances for them when needed. I've run into this issue, because I needed them to be instances of `Binary` and `Hashable`, for example, but there's certainly a ton of additional uses cases.

**Comment by hvr** [comment]
Sounds a bit like a

duplicate of #45

**Comment by peti** [comment]
Oh, yes, indeed.
